// packages/examples/vue/src/demos/row-height/RowHeightDemo.vue
<template>
  <SimpleTable
    :default-headers="rowHeightConfig.headers"
    :rows="rowHeightConfig.rows"
    :height="height"
    :theme="theme"
    :custom-theme="rowHeightConfig.tableProps.customTheme"
  />
</template>

<script setup lang="ts">
import {SimpleTable} from "@simple-table/vue";import type { Theme } from "@simple-table/vue";
import { rowHeightConfig } from "./row-height.demo-data";
import "@simple-table/vue/styles.css";

withDefaults(defineProps<{ height?: string | number; theme?: Theme }>(), {
  height: "400px",
});
</script>

// packages/examples/svelte/src/demos/row-height/RowHeightDemo.svelte
<script lang="ts">
  import {SimpleTable} from "@simple-table/svelte";  import type { Theme } from "@simple-table/svelte";
  import { rowHeightConfig } from "./row-height.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
</script>

<SimpleTable
  defaultHeaders={rowHeightConfig.headers}
  rows={rowHeightConfig.rows}
  {height}
  {theme}
  customTheme={rowHeightConfig.tableProps.customTheme}
/>
