// packages/examples/svelte/src/demos/billing/BillingNameCell.svelte
<script lang="ts">
  import type { CellRendererProps } from "@simple-table/svelte";
  import type { BillingRow } from "./billing.demo-data";

  let { row }: CellRendererProps = $props();
  const d = $derived(row as unknown as BillingRow);
</script>

{#if d.type === "account"}
  <span style="font-weight: 600">{d.name}</span>
{:else}
  {d.name}
{/if}

// packages/examples/angular/src/demos/billing/billing-name-cell.component.ts
import { Component, Input } from "@angular/core";
import type { Row } from "@simple-table/angular";
import type { BillingRow } from "./billing.demo-data";

@Component({
  standalone: true,
  selector: "demo-billing-name-cell",
  template: `
    @if (isAccount) {
      <span style="font-weight:600;">{{ name }}</span>
    } @else {
      {{ name }}
    }
  `,
})
export class BillingNameCellComponent {
  @Input({ required: true }) row!: Row;

  get d(): BillingRow {
    return this.row as unknown as BillingRow;
  }

  get isAccount(): boolean {
    return this.d.type === "account";
  }

  get name(): string {
    return this.d.name;
  }
}
