// packages/examples/vue/src/demos/row-grouping/RowGroupingDemo.vue
<template>
  <div style="display: flex; flex-direction: column; gap: 12px">
    <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center">
      <span style="font-size: 13px; font-weight: 600; margin-right: 8px">Control Expansion:</span>
      <button :style="btnStyle('#28a745')" @click="expandAll" title="expandAll()">Expand All</button>
      <button :style="btnStyle('#dc3545')" @click="collapseAll" title="collapseAll()">Collapse All</button>
      <button :style="btnStyle('#007bff')" @click="onlyDivisions" title="expandDepth(0)">Only Divisions</button>
      <button :style="btnStyle('#6c757d')" @click="divisionsAndDepts" title="setExpandedDepths(new Set([0, 1]))">Divisions + Departments</button>
      <button :style="btnStyle('#6f42c1')" @click="toggleDivisions" title="toggleDepth(0)">Toggle Divisions</button>
    </div>
    <SimpleTable
      ref="tableRef"
      :default-headers="rowGroupingConfig.headers"
      :rows="rowGroupingConfig.rows"
      :row-grouping="rowGroupingConfig.tableProps.rowGrouping"
      :enable-sticky-parents="true"
      :get-row-id="rowGroupingConfig.tableProps.getRowId"
      :column-resizing="true"
      :height="height"
      :theme="theme"
    />
  </div>
</template>

<script setup lang="ts">
import { ref } from "vue";
import {SimpleTable} from "@simple-table/vue";import type { Theme, TableAPI } from "@simple-table/vue";
import { rowGroupingConfig } from "./row-grouping.demo-data";
import "@simple-table/vue/styles.css";

withDefaults(defineProps<{ height?: string | number; theme?: Theme }>(), {
  height: "400px",
});

const tableRef = ref<{ getAPI: () => TableAPI | null } | null>(null);

function btnStyle(color: string) {
  return {
    padding: "6px 12px",
    background: color,
    color: "white",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "12px",
    fontWeight: "500",
  };
}

function expandAll() { tableRef.value?.getAPI()?.expandAll(); }
function collapseAll() { tableRef.value?.getAPI()?.collapseAll(); }
function onlyDivisions() { tableRef.value?.getAPI()?.collapseAll(); tableRef.value?.getAPI()?.expandDepth(0); }
function divisionsAndDepts() { tableRef.value?.getAPI()?.setExpandedDepths(new Set([0, 1])); }
function toggleDivisions() { tableRef.value?.getAPI()?.toggleDepth(0); }
</script>

// packages/examples/angular/src/demos/row-grouping/row-grouping-demo.component.ts
import { Component, Input, ViewChild } from "@angular/core";
import {SimpleTableComponent} from "@simple-table/angular";import type { AngularHeaderObject, Row, Theme } from "@simple-table/angular";
import { rowGroupingConfig } from "./row-grouping.demo-data";
import "@simple-table/angular/styles.css";

@Component({
  selector: "row-grouping-demo",
  standalone: true,
  imports: [SimpleTableComponent],
  template: `
    <div style="display: flex; flex-direction: column; gap: 12px">
      <div style="display: flex; gap: 8px; flex-wrap: wrap; align-items: center">
        <span style="font-size: 13px; font-weight: 600; margin-right: 8px">Control Expansion:</span>
        <button [style.padding]="'6px 12px'" [style.background]="'#28a745'" [style.color]="'white'" [style.border]="'none'" [style.borderRadius]="'4px'" [style.cursor]="'pointer'" [style.fontSize]="'12px'" [style.fontWeight]="500" (click)="expandAll()" title="expandAll()">Expand All</button>
        <button [style.padding]="'6px 12px'" [style.background]="'#dc3545'" [style.color]="'white'" [style.border]="'none'" [style.borderRadius]="'4px'" [style.cursor]="'pointer'" [style.fontSize]="'12px'" [style.fontWeight]="500" (click)="collapseAll()" title="collapseAll()">Collapse All</button>
        <button [style.padding]="'6px 12px'" [style.background]="'#007bff'" [style.color]="'white'" [style.border]="'none'" [style.borderRadius]="'4px'" [style.cursor]="'pointer'" [style.fontSize]="'12px'" [style.fontWeight]="500" (click)="onlyDivisions()" title="expandDepth(0)">Only Divisions</button>
        <button [style.padding]="'6px 12px'" [style.background]="'#6c757d'" [style.color]="'white'" [style.border]="'none'" [style.borderRadius]="'4px'" [style.cursor]="'pointer'" [style.fontSize]="'12px'" [style.fontWeight]="500" (click)="divisionsAndDepts()" title="setExpandedDepths(new Set([0, 1]))">Divisions + Departments</button>
        <button [style.padding]="'6px 12px'" [style.background]="'#6f42c1'" [style.color]="'white'" [style.border]="'none'" [style.borderRadius]="'4px'" [style.cursor]="'pointer'" [style.fontSize]="'12px'" [style.fontWeight]="500" (click)="toggleDivisions()" title="toggleDepth(0)">Toggle Divisions</button>
      </div>
      <simple-table
        #simpleTable
        [rows]="rows"
        [defaultHeaders]="headers"
        [height]="height"
        [theme]="theme"
        [rowGrouping]="grouping"
        [enableStickyParents]="true"
        [getRowId]="getRowId"
        [columnResizing]="true"
      ></simple-table>
    </div>
  `,
})
export class RowGroupingDemoComponent {
  @ViewChild("simpleTable") tableRef!: SimpleTableComponent;
  @Input() height: string | number = "400px";
  @Input() theme?: Theme;

  readonly rows: Row[] = rowGroupingConfig.rows;
  readonly headers: AngularHeaderObject[] = rowGroupingConfig.headers;
  readonly grouping = rowGroupingConfig.tableProps.rowGrouping;
  readonly getRowId = rowGroupingConfig.tableProps.getRowId;

  expandAll() { this.tableRef.getAPI()?.expandAll(); }
  collapseAll() { this.tableRef.getAPI()?.collapseAll(); }
  onlyDivisions() { this.tableRef.getAPI()?.collapseAll(); this.tableRef.getAPI()?.expandDepth(0); }
  divisionsAndDepts() { this.tableRef.getAPI()?.setExpandedDepths(new Set([0, 1])); }
  toggleDivisions() { this.tableRef.getAPI()?.toggleDepth(0); }
}
