// packages/examples/angular/src/demos/column-width/column-width-demo.component.ts
import { Component, Input, OnInit, OnDestroy } from "@angular/core";
import {SimpleTableComponent} from "@simple-table/angular";import type { AngularHeaderObject, Row, Theme } from "@simple-table/angular";
import { columnWidthConfig } from "./column-width.demo-data";
import "@simple-table/angular/styles.css";

@Component({
  selector: "column-width-demo",
  standalone: true,
  imports: [SimpleTableComponent],
  template: `
    <simple-table
      [autoExpandColumns]="!isMobile"
      [columnResizing]="true"
      [rows]="rows"
      [defaultHeaders]="headers"
      [height]="height"
      [theme]="theme"
    ></simple-table>
  `,
})
export class ColumnWidthDemoComponent implements OnInit, OnDestroy {
  @Input() height: string | number = "400px";
  @Input() theme?: Theme;

  readonly rows: Row[] = columnWidthConfig.rows;
  readonly headers: AngularHeaderObject[] = columnWidthConfig.headers;
  isMobile = false;

  private checkMobile = () => { this.isMobile = window.innerWidth < 768; };

  ngOnInit() {
    this.checkMobile();
    window.addEventListener("resize", this.checkMobile);
  }

  ngOnDestroy() {
    window.removeEventListener("resize", this.checkMobile);
  }
}

// packages/examples/svelte/src/demos/column-width/ColumnWidthDemo.svelte
<script lang="ts">
  import {SimpleTable} from "@simple-table/svelte";  import type { Theme } from "@simple-table/svelte";
  import { columnWidthConfig } from "./column-width.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
  let isMobile = $state(false);

  function checkMobile() {
    isMobile = window.innerWidth < 768;
  }

  $effect(() => {
    checkMobile();
    window.addEventListener("resize", checkMobile);
    return () => window.removeEventListener("resize", checkMobile);
  });
</script>

<SimpleTable
  autoExpandColumns={!isMobile}
  columnResizing={true}
  defaultHeaders={columnWidthConfig.headers}
  rows={columnWidthConfig.rows}
  {height}
  {theme}
/>
