// packages/examples/angular/src/demos/value-formatter/value-formatter-demo.component.ts
import { Component, Input } from "@angular/core";
import {SimpleTableComponent} from "@simple-table/angular";import type { AngularHeaderObject, Row, Theme } from "@simple-table/angular";
import { valueFormatterConfig } from "./value-formatter.demo-data";
import "@simple-table/angular/styles.css";

@Component({
  selector: "value-formatter-demo",
  standalone: true,
  imports: [SimpleTableComponent],
  template: `
    <simple-table
      [rows]="rows"
      [defaultHeaders]="headers"
      [height]="height"
      [theme]="theme"
      [selectableCells]="selectableCellsProp"
    ></simple-table>
  `,
})
export class ValueFormatterDemoComponent {
  @Input() height: string | number = "400px";
  @Input() theme?: Theme;

  readonly rows: Row[] = valueFormatterConfig.rows;
  readonly headers: AngularHeaderObject[] = valueFormatterConfig.headers;
  readonly selectableCellsProp = valueFormatterConfig.tableProps.selectableCells;
}

// packages/examples/svelte/src/demos/value-formatter/ValueFormatterDemo.svelte
<script lang="ts">
  import {SimpleTable} from "@simple-table/svelte";  import type { Theme } from "@simple-table/svelte";
  import { valueFormatterConfig } from "./value-formatter.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
</script>

<SimpleTable
  defaultHeaders={valueFormatterConfig.headers}
  rows={valueFormatterConfig.rows}
  {height}
  {theme}
  selectableCells={valueFormatterConfig.tableProps.selectableCells}
/>
