// packages/examples/svelte/src/demos/pagination/PaginationDemo.svelte
<script lang="ts">
  import {SimpleTable} from "@simple-table/svelte";  import type { Theme } from "@simple-table/svelte";
  import { paginationConfig, paginationData, PAGINATION_ROWS_PER_PAGE } from "./pagination.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height, theme }: { height?: string | number; theme?: Theme } = $props();

  let rows = $state(paginationData.slice(0, PAGINATION_ROWS_PER_PAGE));
  let isLoading = $state(false);

  const onNextPage = async (pageIndex: number) => {
    const startIndex = pageIndex * PAGINATION_ROWS_PER_PAGE;
    const endIndex = startIndex + PAGINATION_ROWS_PER_PAGE;

    isLoading = true;
    await new Promise((resolve) => setTimeout(resolve, 800));
    const newPageData = paginationData.slice(startIndex, endIndex);

    if (newPageData.length === 0 || rows.length > startIndex) {
      isLoading = false;
      return false;
    }

    rows = [...rows, ...newPageData];
    isLoading = false;
    return true;
  };
</script>

<SimpleTable
  defaultHeaders={paginationConfig.headers}
  height={height ?? "auto"}
  {isLoading}
  {onNextPage}
  {rows}
  rowsPerPage={PAGINATION_ROWS_PER_PAGE}
  shouldPaginate={true}
  {theme}
/>

// packages/examples/angular/src/demos/pagination/pagination-demo.component.ts
import { Component, Input } from "@angular/core";
import {SimpleTableComponent} from "@simple-table/angular";import type { AngularHeaderObject, Row, Theme } from "@simple-table/angular";
import { paginationConfig, paginationData, PAGINATION_ROWS_PER_PAGE } from "./pagination.demo-data";
import "@simple-table/angular/styles.css";

@Component({
  selector: "pagination-demo",
  standalone: true,
  imports: [SimpleTableComponent],
  template: `
    <simple-table
      [rows]="rows"
      [defaultHeaders]="headers"
      [height]="height"
      [theme]="theme"
      [shouldPaginate]="true"
      [rowsPerPage]="rowsPerPage"
      [isLoading]="isLoading"
      [onNextPage]="onNextPage"
    ></simple-table>
  `,
})
export class PaginationDemoComponent {
  @Input() height: string | number = "auto";
  @Input() theme?: Theme;

  readonly headers: AngularHeaderObject[] = paginationConfig.headers;
  readonly rowsPerPage = PAGINATION_ROWS_PER_PAGE;
  rows: Row[] = paginationData.slice(0, PAGINATION_ROWS_PER_PAGE);
  isLoading = false;

  onNextPage = async (pageIndex: number): Promise<boolean> => {
    const startIndex = pageIndex * PAGINATION_ROWS_PER_PAGE;
    const endIndex = startIndex + PAGINATION_ROWS_PER_PAGE;

    this.isLoading = true;
    await new Promise((resolve) => setTimeout(resolve, 800));
    const newPageData = paginationData.slice(startIndex, endIndex);

    if (newPageData.length === 0 || this.rows.length > startIndex) {
      this.isLoading = false;
      return false;
    }

    this.rows = [...this.rows, ...newPageData];
    this.isLoading = false;
    return true;
  };
}
