// packages/examples/angular/src/demos/music/music-tag.component.ts
import { Component, Input } from "@angular/core";
import type { Theme } from "@simple-table/angular";
import { getMusicThemeColors } from "./music.demo-data";

@Component({
  standalone: true,
  selector: "demo-music-tag",
  template: `
    <span
      [style.background-color]="styles.bg"
      [style.color]="styles.text"
      [style.padding]="'0 7px'"
      [style.font-size]="'11px'"
      [style.line-height]="'20px'"
      [style.border-radius]="'4px'"
      [style.display]="'inline-block'"
      [style.border]="styles.border"
      >{{ text }}</span>
  `,
})
export class MusicTagComponent {
  @Input({ required: true }) text!: string;
  @Input({ required: true }) variant!: "green" | "red" | "default";
  @Input() theme?: Theme;

  get styles(): { bg: string; text: string; border: string } {
    const c = getMusicThemeColors(this.theme);
    const colorMap: Record<string, { bg: string; text: string; border?: string }> = {
      green: { bg: c.successBg, text: c.success },
      red: { bg: c.errorBg, text: c.error },
      default: { bg: c.tagBg, text: c.tagText, border: `1px solid ${c.tagBorder}` },
    };
    const s = colorMap[this.variant] || colorMap.default;
    return { bg: s.bg, text: s.text, border: s.border ?? "none" };
  }
}

// packages/examples/svelte/src/demos/music/MusicTag.svelte
<script lang="ts">
  let {
    text,
    variant,
    c,
  }: {
    text: string;
    variant: "green" | "red" | "default";
    c: Record<string, string>;
  } = $props();

  const s = $derived.by(() => {
    const colorMap: Record<string, { bg: string; text: string; border?: string }> = {
      green: { bg: c.successBg, text: c.success },
      red: { bg: c.errorBg, text: c.error },
      default: { bg: c.tagBg, text: c.tagText, border: `1px solid ${c.tagBorder}` },
    };
    return colorMap[variant] || colorMap.default;
  });
</script>

<span
  style="background-color:{s.bg};color:{s.text};padding:0 7px;font-size:11px;line-height:20px;border-radius:4px;display:inline-block;{s.border
    ? `border:${s.border};`
    : ''}"
>{text}</span>
