// packages/examples/vue/src/demos/column-editor-custom-renderer/ColumnEditorCustomRow.vue
<script lang="ts">
import { defineComponent, h } from "vue";
import type { ColumnEditorRowRendererProps } from "@simple-table/vue";

export default defineComponent({
  name: "ColumnEditorCustomRow",
  props: {
    header: { type: Object, required: true },
    components: { type: Object, required: true },
  },
  setup(props: ColumnEditorRowRendererProps) {
    return () =>
      h(
        "div",
        {
          style: {
            display: "flex",
            alignItems: "center",
            gap: "8px",
            padding: "6px 8px",
            borderRadius: "6px",
            background: "#f8fafc",
            marginBottom: "4px",
          },
        },
        [
          props.components.checkbox != null
            ? h("span", null, [props.components.checkbox as object])
            : null,
          h(
            "span",
            { style: { flex: "1", fontSize: "13px", fontWeight: "500" } },
            props.header.label,
          ),
          props.components.dragIcon != null
            ? h(
                "span",
                { style: { cursor: "grab", opacity: "0.5" } },
                [props.components.dragIcon as object],
              )
            : null,
        ].filter(Boolean),
      );
  },
});
</script>

// packages/examples/svelte/src/demos/column-editor-custom-renderer/ColumnEditorCustomRow.svelte
<script lang="ts">
  import type { ColumnEditorRowRendererProps } from "@simple-table/svelte";

  let { header, components }: ColumnEditorRowRendererProps = $props();

  let checkboxHost: HTMLSpanElement | undefined = $state(undefined);
  let dragHost: HTMLSpanElement | undefined = $state(undefined);

  function attach(slot: unknown, host: HTMLElement | undefined): void {
    if (!host) return;
    host.replaceChildren();
    if (slot == null) return;
    if (typeof slot === "string") {
      host.textContent = slot;
    } else if (slot instanceof Node) {
      host.appendChild(slot);
    }
  }

  $effect(() => {
    attach(components.checkbox, checkboxHost);
  });

  $effect(() => {
    attach(components.dragIcon, dragHost);
  });
</script>

<div
  style="display: flex; align-items: center; gap: 8px; padding: 6px 8px; border-radius: 6px; background: #f8fafc; margin-bottom: 4px;"
>
  {#if components.checkbox}
    <span bind:this={checkboxHost}></span>
  {/if}
  <span style="flex: 1; font-size: 13px; font-weight: 500;">{header.label}</span>
  {#if components.dragIcon}
    <span bind:this={dragHost} style="cursor: grab; opacity: 0.5;"></span>
  {/if}
</div>
