// packages/examples/svelte/src/demos/crm/CrmAiScoreCell.svelte
<script lang="ts">
  import type { CellRendererProps } from "@simple-table/svelte";
  import type { CRMLead } from "./crm.demo-data";

  let { row }: CellRendererProps = $props();
  const d = $derived(row as unknown as CRMLead);
</script>

<div style="font-size:0.875rem;">{"🔥".repeat(d.aiScore)}</div>

// packages/examples/angular/src/demos/crm/crm-ai-score-cell.component.ts
import { Component, Input } from "@angular/core";
import type { Row } from "@simple-table/angular";
import type { CRMLead } from "./crm.demo-data";

@Component({
  standalone: true,
  selector: "demo-crm-ai-score",
  template: `<div style="font-size:0.875rem;">{{ fire }}</div>`,
})
export class CrmAiScoreCellComponent {
  @Input({ required: true }) row!: Row;

  get d(): CRMLead {
    return this.row as unknown as CRMLead;
  }

  get fire(): string {
    return "🔥".repeat(this.d.aiScore);
  }
}
