// packages/examples/angular/src/demos/cell-renderer/cell-renderer-demo.component.ts
import { Component, Input } from "@angular/core";
import { SimpleTableComponent } from "@simple-table/angular";
import type { AngularCellRenderer, AngularHeaderObject, Row, Theme } from "@simple-table/angular";
import { cellRendererConfig } from "./cell-renderer.demo-data";
import { CrProgressCellComponent } from "./cr-progress-cell.component";
import { CrRatingCellComponent } from "./cr-rating-cell.component";
import { CrStatusCellComponent } from "./cr-status-cell.component";
import { CrTagsCellComponent } from "./cr-tags-cell.component";
import { CrTeamMembersCellComponent } from "./cr-team-members-cell.component";
import { CrVerifiedCellComponent } from "./cr-verified-cell.component";
import { CrWebsiteCellComponent } from "./cr-website-cell.component";
import "@simple-table/angular/styles.css";

const RENDERERS: Partial<Record<string, AngularCellRenderer>> = {
  teamMembers: CrTeamMembersCellComponent,
  website: CrWebsiteCellComponent,
  status: CrStatusCellComponent,
  progress: CrProgressCellComponent,
  rating: CrRatingCellComponent,
  verified: CrVerifiedCellComponent,
  tags: CrTagsCellComponent,
};

@Component({
  selector: "cell-renderer-demo",
  standalone: true,
  imports: [SimpleTableComponent],
  template: `
    <simple-table
      [rows]="rows"
      [defaultHeaders]="headers"
      [height]="height"
      [theme]="theme"
      [selectableCells]="true"
      [customTheme]="{ rowHeight: 48 }"
    ></simple-table>
  `,
})
export class CellRendererDemoComponent {
  @Input() height: string | number = "400px";
  @Input() theme?: Theme;

  readonly rows: Row[] = cellRendererConfig.rows;
  readonly headers: AngularHeaderObject[] = cellRendererConfig.headers.map((h): AngularHeaderObject => {
    const cellRenderer = RENDERERS[String(h.accessor)];
    return cellRenderer ? { ...h, cellRenderer } : { ...h };
  });
}

// packages/examples/svelte/src/demos/cell-renderer/CellRendererDemo.svelte
<script lang="ts">
  import { SimpleTable } from "@simple-table/svelte";
  import type { Theme, SvelteHeaderObject } from "@simple-table/svelte";
  import { cellRendererConfig } from "./cell-renderer.demo-data";
  import CrTeamMembersCell from "./CrTeamMembersCell.svelte";
  import CrWebsiteCell from "./CrWebsiteCell.svelte";
  import CrStatusCell from "./CrStatusCell.svelte";
  import CrProgressCell from "./CrProgressCell.svelte";
  import CrRatingCell from "./CrRatingCell.svelte";
  import CrVerifiedCell from "./CrVerifiedCell.svelte";
  import CrTagsCell from "./CrTagsCell.svelte";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();

  const RENDERERS: Record<string, unknown> = {
    teamMembers: CrTeamMembersCell,
    website: CrWebsiteCell,
    status: CrStatusCell,
    progress: CrProgressCell,
    rating: CrRatingCell,
    verified: CrVerifiedCell,
    tags: CrTagsCell,
  };

  const headers: SvelteHeaderObject[] = cellRendererConfig.headers.map((h) => {
    const cellRenderer = RENDERERS[h.accessor as string];
    return cellRenderer ? { ...h, cellRenderer } : { ...h };
  });
</script>

<SimpleTable
  defaultHeaders={headers}
  rows={cellRendererConfig.rows}
  {height}
  {theme}
  selectableCells={cellRendererConfig.tableProps.selectableCells}
  customTheme={cellRendererConfig.tableProps.customTheme}
/>
