// packages/examples/angular/src/demos/cell-renderer/cr-website-cell.component.ts
import { Component, Input } from "@angular/core";
import type { CellValue } from "@simple-table/angular";

@Component({
  standalone: true,
  selector: "demo-cr-website",
  template: `
    <span>🌐 <a class="crw" [href]="'https://' + url" target="_blank" rel="noopener noreferrer">{{ url }}</a></span>
  `,
  styles: [
    `
      .crw {
        color: #2563eb;
        text-decoration: none;
      }
      .crw:hover {
        text-decoration: underline;
      }
    `,
  ],
})
export class CrWebsiteCellComponent {
  @Input() value!: CellValue;

  get url(): string {
    return String(this.value);
  }
}

// packages/examples/svelte/src/demos/cell-renderer/CrWebsiteCell.svelte
<script lang="ts">
  import type { CellRendererProps } from "@simple-table/svelte";

  let { value }: CellRendererProps = $props();
  const url = $derived(String(value));
</script>

<span>🌐 <a class="crw" href="https://{url}" target="_blank" rel="noopener noreferrer">{url}</a></span>

<style>
  .crw {
    color: #2563eb;
    text-decoration: none;
  }
  .crw:hover {
    text-decoration: underline;
  }
</style>
