// packages/examples/angular/src/demos/external-filter/external-filter-demo.component.ts
import { Component, Input } from "@angular/core";
import {SimpleTableComponent} from "@simple-table/angular";import type { AngularHeaderObject, Row, TableFilterState, Theme } from "@simple-table/angular";
import { externalFilterConfig, matchesFilter } from "./external-filter.demo-data";
import "@simple-table/angular/styles.css";

@Component({
  selector: "external-filter-demo",
  standalone: true,
  imports: [SimpleTableComponent],
  template: `
    <simple-table
      [rows]="filteredRows"
      [defaultHeaders]="headers"
      [externalFilterHandling]="true"
      [columnResizing]="true"
      [height]="height"
      [theme]="theme"
      [onFilterChange]="handleFilterChange"
    ></simple-table>
  `,
})
export class ExternalFilterDemoComponent {
  @Input() height: string | number = "400px";
  @Input() theme?: Theme;

  readonly headers: AngularHeaderObject[] = externalFilterConfig.headers;
  private filters: TableFilterState = {};

  handleFilterChange = (newFilters: TableFilterState) => {
    this.filters = newFilters;
  };

  get filteredRows(): Row[] {
    const entries = Object.entries(this.filters);
    if (entries.length === 0) return externalFilterConfig.rows as Row[];

    return (externalFilterConfig.rows as Row[]).filter((row) =>
      entries.every(([accessor, filter]) =>
        matchesFilter(row[accessor] as any, filter)
      )
    );
  }
}

// packages/examples/svelte/src/demos/external-filter/ExternalFilterDemo.svelte
<script lang="ts">
  import {SimpleTable} from "@simple-table/svelte";  import type { Theme, TableFilterState } from "@simple-table/svelte";
  import { externalFilterConfig, matchesFilter } from "./external-filter.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();

  let filters = $state<TableFilterState>({});

  let filteredRows = $derived.by(() => {
    const entries = Object.entries(filters);
    if (entries.length === 0) return externalFilterConfig.rows;

    return externalFilterConfig.rows.filter((row) =>
      entries.every(([accessor, filter]) =>
        matchesFilter(row[accessor as keyof typeof row] as any, filter)
      )
    );
  });

  function handleFilterChange(newFilters: TableFilterState) {
    filters = newFilters;
  }
</script>

<SimpleTable
  defaultHeaders={externalFilterConfig.headers}
  rows={filteredRows}
  externalFilterHandling={true}
  columnResizing={true}
  onFilterChange={handleFilterChange}
  {height}
  {theme}
/>
