// packages/examples/svelte/src/demos/manufacturing/ManufacturingDemo.svelte
<script lang="ts">
  import { SimpleTable } from "@simple-table/svelte";
  import type { Theme, SvelteHeaderObject } from "@simple-table/svelte";
  import { manufacturingConfig } from "./manufacturing.demo-data";
  import MfgProductLineCell from "./MfgProductLineCell.svelte";
  import MfgStationCell from "./MfgStationCell.svelte";
  import MfgStatusCell from "./MfgStatusCell.svelte";
  import MfgBoldNumberCell from "./MfgBoldNumberCell.svelte";
  import MfgCycletimeCell from "./MfgCycletimeCell.svelte";
  import MfgEfficiencyCell from "./MfgEfficiencyCell.svelte";
  import MfgDefectRateCell from "./MfgDefectRateCell.svelte";
  import MfgDowntimeCell from "./MfgDowntimeCell.svelte";
  import MfgUtilizationCell from "./MfgUtilizationCell.svelte";
  import MfgMaintenanceDateCell from "./MfgMaintenanceDateCell.svelte";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();

  const rendererMap: Record<string, unknown> = {
    productLine: MfgProductLineCell,
    station: MfgStationCell,
    status: MfgStatusCell,
    outputRate: MfgBoldNumberCell,
    cycletime: MfgCycletimeCell,
    efficiency: MfgEfficiencyCell,
    defectRate: MfgDefectRateCell,
    defectCount: MfgBoldNumberCell,
    downtime: MfgDowntimeCell,
    utilization: MfgUtilizationCell,
    energy: MfgBoldNumberCell,
    maintenanceDate: MfgMaintenanceDateCell,
  };

  const headers = $derived.by((): SvelteHeaderObject[] =>
    manufacturingConfig.headers.map((h) => {
      const cellRenderer = rendererMap[h.accessor as string];
      return cellRenderer ? { ...h, cellRenderer } : { ...h };
    }),
  );
</script>

<SimpleTable
  columnResizing={true}
  columnReordering={true}
  defaultHeaders={headers}
  {height}
  rowGrouping={["stations"]}
  rows={manufacturingConfig.rows}
  selectableCells={true}
  {theme}
/>

// packages/examples/angular/src/demos/manufacturing/manufacturing-demo.component.ts
import { Component, Input } from "@angular/core";
import { SimpleTableComponent, asRows } from "@simple-table/angular";
import type { AngularCellRenderer, AngularHeaderObject, Theme } from "@simple-table/angular";
import { manufacturingConfig } from "./manufacturing.demo-data";
import {
  MfgCycletimeCellComponent,
  MfgDefectRateCellComponent,
  MfgDowntimeCellComponent,
  MfgEfficiencyCellComponent,
  MfgMaintenanceDateCellComponent,
  MfgNumberBoldParentCellComponent,
  MfgProductLineCellComponent,
  MfgStationCellComponent,
  MfgStatusCellComponent,
  MfgUtilizationCellComponent,
} from "./manufacturing-cell-components";
import "@simple-table/angular/styles.css";

const RENDERERS: Partial<Record<string, AngularCellRenderer>> = {
  productLine: MfgProductLineCellComponent,
  station: MfgStationCellComponent,
  status: MfgStatusCellComponent,
  outputRate: MfgNumberBoldParentCellComponent,
  cycletime: MfgCycletimeCellComponent,
  efficiency: MfgEfficiencyCellComponent,
  defectRate: MfgDefectRateCellComponent,
  defectCount: MfgNumberBoldParentCellComponent,
  downtime: MfgDowntimeCellComponent,
  utilization: MfgUtilizationCellComponent,
  energy: MfgNumberBoldParentCellComponent,
  maintenanceDate: MfgMaintenanceDateCellComponent,
};

function getHeaders(): AngularHeaderObject[] {
  return manufacturingConfig.headers.map((h): AngularHeaderObject => {
    const cellRenderer = RENDERERS[String(h.accessor)];
    return cellRenderer ? { ...h, cellRenderer } : { ...h };
  });
}

@Component({
  selector: "manufacturing-demo",
  standalone: true,
  imports: [SimpleTableComponent],
  template: `
    <simple-table
      [columnResizing]="true"
      [columnReordering]="true"
      [defaultHeaders]="headers"
      [height]="height"
      [rowGrouping]="grouping"
      [rows]="rows"
      [selectableCells]="true"
      [theme]="theme"
    ></simple-table>
  `,
})
export class ManufacturingDemoComponent {
  @Input() height: string | number = "400px";
  @Input() theme?: Theme;

  readonly grouping = ["stations"];
  readonly rows = asRows(manufacturingConfig.rows);
  readonly headers: AngularHeaderObject[] = getHeaders();
}
