// packages/examples/svelte/src/demos/sales/SalesIsWonCell.svelte
<script lang="ts">
  import type { CellRendererProps } from "@simple-table/svelte";
  import type { SalesRow } from "./sales.demo-data";

  let { row }: CellRendererProps = $props();
  const d = $derived(row as unknown as SalesRow);
  const s = $derived(d.isWon ? { bg: "#f6ffed", text: "#2a6a0d" } : { bg: "#fff1f0", text: "#a8071a" });
</script>

{#if row.isWon === "—"}
  —
{:else}
  <span
    style="background-color:{s.bg};color:{s.text};padding:0 7px;font-size:12px;line-height:20px;border-radius:2px;display:inline-block;"
    >{d.isWon ? "Won" : "Lost"}</span>
{/if}

// packages/examples/angular/src/demos/sales/sales-is-won-cell.component.ts
import { Component, Input } from "@angular/core";
import type { Row } from "@simple-table/angular";
import type { SalesRow } from "./sales.demo-data";

@Component({
  standalone: true,
  selector: "demo-sales-is-won",
  template: `
    @if (row.isWon === "—") {
      —
    } @else {
      <span
        style="padding:0 7px;font-size:12px;line-height:20px;border-radius:2px;display:inline-block;"
        [style.background-color]="pill.bg"
        [style.color]="pill.text"
        >{{ d.isWon ? "Won" : "Lost" }}</span>
    }
  `,
})
export class SalesIsWonCellComponent {
  @Input({ required: true }) row!: Row;

  get d(): SalesRow {
    return this.row as unknown as SalesRow;
  }

  get pill(): { bg: string; text: string } {
    return this.d.isWon
      ? { bg: "#f6ffed", text: "#2a6a0d" }
      : { bg: "#fff1f0", text: "#a8071a" };
  }
}
