// packages/examples/svelte/src/demos/sales/SalesCommissionCell.svelte
<script lang="ts">
  import type { CellRendererProps } from "@simple-table/svelte";
  import { getThemeColors } from "./sales.demo-data";
  import type { SalesRow } from "./sales.demo-data";

  let { row, theme }: CellRendererProps = $props();
  const colors = $derived(getThemeColors(theme));
  const d = $derived(row as unknown as SalesRow);
</script>

{#if row.commission === "—"}
  —
{:else if d.commission === 0}
  <span style="color:{colors.grayMuted};">$0.00</span>
{:else}
  ${d.commission.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
{/if}

// packages/examples/angular/src/demos/sales/sales-commission-cell.component.ts
import { Component, Input } from "@angular/core";
import type { Row, Theme } from "@simple-table/angular";
import { getThemeColors } from "./sales.demo-data";
import type { SalesRow } from "./sales.demo-data";

@Component({
  standalone: true,
  selector: "demo-sales-commission",
  template: `
    @if (row.commission === "—") {
      —
    } @else if (d.commission === 0) {
      <span [style.color]="c.grayMuted">$0.00</span>
    } @else {
      {{ commissionText }}
    }
  `,
})
export class SalesCommissionCellComponent {
  @Input({ required: true }) row!: Row;
  @Input() theme?: Theme;

  get d(): SalesRow {
    return this.row as unknown as SalesRow;
  }

  get c(): ReturnType<typeof getThemeColors> {
    return getThemeColors(this.theme);
  }

  get commissionText(): string {
    return `$${this.d.commission.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
  }
}
