// packages/examples/svelte/src/demos/sales/SalesDealProfitCell.svelte
<script lang="ts">
  import type { CellRendererProps } from "@simple-table/svelte";
  import { getThemeColors } from "./sales.demo-data";
  import type { SalesRow } from "./sales.demo-data";

  let { row, theme }: CellRendererProps = $props();
  const colors = $derived(getThemeColors(theme));
  const d = $derived(row as unknown as SalesRow);
  const style = $derived.by(() => {
    if (row.dealProfit === "—") return null;
    if (d.dealProfit === 0) return { kind: "zero" as const };
    let color = colors.gray;
    let fontWeight = "normal";
    if (d.dealProfit > 50000) {
      color = colors.success.high.color;
      fontWeight = colors.success.high.fontWeight;
    } else if (d.dealProfit > 20000) color = colors.success.medium;
    else if (d.dealProfit > 10000) color = colors.success.low;
    return {
      kind: "val" as const,
      color,
      weight: fontWeight,
      text: `$${d.dealProfit.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
    };
  });
</script>

{#if row.dealProfit === "—"}
  —
{:else if style?.kind === "zero"}
  <span style="color:{colors.grayMuted};">$0.00</span>
{:else if style?.kind === "val"}
  <span style="color:{style.color};font-weight:{style.weight};">{style.text}</span>
{/if}

// packages/examples/angular/src/demos/sales/sales-deal-profit-cell.component.ts
import { Component, Input } from "@angular/core";
import type { Row, Theme } from "@simple-table/angular";
import { getThemeColors } from "./sales.demo-data";
import type { SalesRow } from "./sales.demo-data";

@Component({
  standalone: true,
  selector: "demo-sales-deal-profit",
  template: `
    @if (row.dealProfit === "—") {
      —
    } @else if (d.dealProfit === 0) {
      <span [style.color]="c.grayMuted">$0.00</span>
    } @else {
      <span [style.color]="textColor" [style.font-weight]="textWeight">{{ profitText }}</span>
    }
  `,
})
export class SalesDealProfitCellComponent {
  @Input({ required: true }) row!: Row;
  @Input() theme?: Theme;

  get d(): SalesRow {
    return this.row as unknown as SalesRow;
  }

  get c(): ReturnType<typeof getThemeColors> {
    return getThemeColors(this.theme);
  }

  get profitText(): string {
    return `$${(this.d.dealProfit as number).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
  }

  get textColor(): string {
    const v = this.d.dealProfit as number;
    const c = this.c;
    if (v > 50000) return c.success.high.color;
    if (v > 20000) return c.success.medium;
    if (v > 10000) return c.success.low;
    return c.gray;
  }

  get textWeight(): string {
    return (this.d.dealProfit as number) > 50000 ? this.c.success.high.fontWeight : "normal";
  }
}
