// packages/examples/svelte/src/demos/cell-clicking/CellClickPriorityCell.svelte
<script lang="ts">
  import type { CellRendererProps } from "@simple-table/svelte";

  let { row }: CellRendererProps = $props();
  const p = $derived(String((row as Record<string, unknown>).priority));
  const color = $derived(p === "High" ? "#ef4444" : p === "Medium" ? "#f59e0b" : "#10b981");
</script>

<span style="color:{color};font-weight:bold;cursor:pointer;" title="Click to filter by priority">{p}</span>

// packages/examples/angular/src/demos/cell-clicking/cell-click-priority-cell.component.ts
import { Component, Input } from "@angular/core";
import type { Row } from "@simple-table/angular";

@Component({
  standalone: true,
  selector: "demo-cell-click-priority",
  template: `
    <span [style.color]="color" style="font-weight:bold;cursor:pointer;" title="Click to filter by priority">{{ priority }}</span>
  `,
})
export class CellClickPriorityCellComponent {
  @Input({ required: true }) row!: Row;

  get priority(): string {
    return String((this.row as Record<string, unknown>)["priority"]);
  }

  get color(): string {
    const p = this.priority;
    if (p === "High") return "#ef4444";
    if (p === "Medium") return "#f59e0b";
    return "#10b981";
  }
}
