// packages/examples/angular/src/demos/column-pinning/column-pinning-demo.component.ts
import { Component, Input } from "@angular/core";
import {SimpleTableComponent} from "@simple-table/angular";import type { AngularHeaderObject, Row, Theme } from "@simple-table/angular";
import { columnPinningConfig } from "./column-pinning.demo-data";
import "@simple-table/angular/styles.css";

@Component({
  selector: "column-pinning-demo",
  standalone: true,
  imports: [SimpleTableComponent],
  template: `
    <simple-table
      [rows]="rows"
      [defaultHeaders]="headers"
      [height]="height"
      [theme]="theme"
      [columnResizing]="columnResizing"
    ></simple-table>
  `,
})
export class ColumnPinningDemoComponent {
  @Input() height: string | number = "400px";
  @Input() theme?: Theme;

  readonly rows: Row[] = columnPinningConfig.rows;
  readonly headers: AngularHeaderObject[] = columnPinningConfig.headers;
  readonly columnResizing = columnPinningConfig.tableProps.columnResizing;
}

// packages/examples/react/src/demos/column-pinning/ColumnPinningDemo.tsx
import {SimpleTable} from "@simple-table/react";import type { Theme } from "@simple-table/react";
import { columnPinningConfig } from "./column-pinning.demo-data";
import "@simple-table/react/styles.css";

const ColumnPinningDemo = ({
  height = "400px",
  theme,
}: {
  height?: string | number;
  theme?: Theme;
}) => {
  return (
    <SimpleTable
      defaultHeaders={columnPinningConfig.headers}
      rows={columnPinningConfig.rows}
      height={height}
      theme={theme}
      columnResizing={columnPinningConfig.tableProps.columnResizing}
    />
  );
};

export default ColumnPinningDemo;
