// packages/examples/svelte/src/demos/collapsible-columns/CollapsibleColumnsDemo.svelte
<script lang="ts">
  import {SimpleTable} from "@simple-table/svelte";  import type { Theme } from "@simple-table/svelte";
  import { collapsibleColumnsConfig } from "./collapsible-columns.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
</script>

<SimpleTable
  defaultHeaders={collapsibleColumnsConfig.headers}
  rows={collapsibleColumnsConfig.rows}
  columnResizing={true}
  editColumns={true}
  selectableCells={true}
  columnReordering={true}
  {height}
  {theme}
/>

// packages/examples/solid/src/demos/collapsible-columns/CollapsibleColumnsDemo.tsx
import {SimpleTable} from "@simple-table/solid";import type { Theme } from "@simple-table/solid";
import { collapsibleColumnsConfig } from "./collapsible-columns.demo-data";
import "@simple-table/solid/styles.css";

export default function CollapsibleColumnsDemo(props: {
  height?: string | number;
  theme?: Theme;
}) {
  return (
    <SimpleTable
      defaultHeaders={collapsibleColumnsConfig.headers}
      rows={collapsibleColumnsConfig.rows}
      columnResizing
      editColumns
      selectableCells
      columnReordering
      height={props.height ?? "400px"}
      theme={props.theme}
    />
  );
}
