// packages/examples/react/src/demos/column-selection/ColumnSelectionDemo.tsx
import {SimpleTable} from "@simple-table/react";import type { Theme } from "@simple-table/react";
import { columnSelectionConfig } from "./column-selection.demo-data";
import "@simple-table/react/styles.css";

const ColumnSelectionDemo = ({
  height = "400px",
  theme,
}: {
  height?: string | number;
  theme?: Theme;
}) => {
  return (
    <SimpleTable
      defaultHeaders={columnSelectionConfig.headers}
      rows={columnSelectionConfig.rows}
      height={height}
      theme={theme}
      selectableColumns={columnSelectionConfig.tableProps.selectableColumns}
    />
  );
};

export default ColumnSelectionDemo;

// packages/examples/angular/src/demos/column-selection/column-selection-demo.component.ts
import { Component, Input } from "@angular/core";
import {SimpleTableComponent} from "@simple-table/angular";import type { AngularHeaderObject, Row, Theme } from "@simple-table/angular";
import { columnSelectionConfig } from "./column-selection.demo-data";
import "@simple-table/angular/styles.css";

@Component({
  selector: "column-selection-demo",
  standalone: true,
  imports: [SimpleTableComponent],
  template: `
    <simple-table
      [rows]="rows"
      [defaultHeaders]="headers"
      [height]="height"
      [theme]="theme"
      [selectableColumns]="selectableColumns"
    ></simple-table>
  `,
})
export class ColumnSelectionDemoComponent {
  @Input() height: string | number = "400px";
  @Input() theme?: Theme;

  readonly rows: Row[] = columnSelectionConfig.rows;
  readonly headers: AngularHeaderObject[] = columnSelectionConfig.headers;
  readonly selectableColumns = columnSelectionConfig.tableProps.selectableColumns;
}
