// packages/examples/svelte/src/demos/cell-editing/CellEditingDemo.svelte
<script lang="ts">
  import {SimpleTable} from "@simple-table/svelte";  import type { Theme, CellChangeProps } from "@simple-table/svelte";
  import { cellEditingConfig } from "./cell-editing.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
  let data = $state([...cellEditingConfig.rows]);

  function handleCellEdit({ accessor, newValue, row }: CellChangeProps) {
    data = data.map((item) =>
      item.id === row.id ? { ...item, [accessor]: newValue } : item
    );
  }
</script>

<SimpleTable
  defaultHeaders={cellEditingConfig.headers}
  rows={data}
  {height}
  {theme}
  onCellEdit={handleCellEdit}
/>

// packages/examples/angular/src/demos/cell-editing/cell-editing-demo.component.ts
import { Component, Input } from "@angular/core";
import {SimpleTableComponent} from "@simple-table/angular";import type { AngularHeaderObject, CellChangeProps, Theme } from "@simple-table/angular";
import { cellEditingConfig } from "./cell-editing.demo-data";
import "@simple-table/angular/styles.css";

@Component({
  selector: "cell-editing-demo",
  standalone: true,
  imports: [SimpleTableComponent],
  template: `
    <simple-table
      [rows]="data"
      [defaultHeaders]="headers"
      [height]="height"
      [theme]="theme"
      (cellEdit)="onCellEdit($event)"
    ></simple-table>
  `,
})
export class CellEditingDemoComponent {
  @Input() height: string | number = "400px";
  @Input() theme?: Theme;

  readonly headers: AngularHeaderObject[] = cellEditingConfig.headers;
  data = [...cellEditingConfig.rows];

  onCellEdit({ accessor, newValue, row }: CellChangeProps): void {
    this.data = this.data.map((item) =>
      item.id === row.id ? { ...item, [accessor]: newValue } : item
    );
  }
}
