// packages/examples/react/src/demos/quick-start/QuickStartDemo.tsx
import {SimpleTable} from "@simple-table/react";import type { Theme } from "@simple-table/react";
import { quickStartConfig } from "./quick-start.demo-data";
import "@simple-table/react/styles.css";

const QuickStartDemo = ({
  height = "300px",
  theme,
}: {
  height?: string | number;
  theme?: Theme;
}) => {
  return (
    <SimpleTable
      defaultHeaders={quickStartConfig.headers}
      rows={quickStartConfig.rows}
      height={height}
      theme={theme}
      editColumns={quickStartConfig.tableProps.editColumns}
      selectableCells={quickStartConfig.tableProps.selectableCells}
      customTheme={quickStartConfig.tableProps.customTheme}
    />
  );
};

export default QuickStartDemo;

// packages/examples/angular/src/demos/quick-start/quick-start-demo.component.ts
import { Component, Input } from "@angular/core";
import {SimpleTableComponent} from "@simple-table/angular";import type { AngularHeaderObject, Row, Theme } from "@simple-table/angular";
import { quickStartConfig } from "./quick-start.demo-data";
import "@simple-table/angular/styles.css";

@Component({
  selector: "quick-start-demo",
  standalone: true,
  imports: [SimpleTableComponent],
  template: `
    <simple-table
      [rows]="rows"
      [defaultHeaders]="headers"
      [height]="height"
      [theme]="theme"
      [editColumns]="editColumnsProp"
      [selectableCells]="selectableCellsProp"
      [customTheme]="customTheme"
    ></simple-table>
  `,
})
export class QuickStartDemoComponent {
  @Input() height: string | number = "300px";
  @Input() theme?: Theme;

  readonly rows: Row[] = quickStartConfig.rows;
  readonly headers: AngularHeaderObject[] = quickStartConfig.headers;
  readonly editColumnsProp = quickStartConfig.tableProps.editColumns;
  readonly selectableCellsProp = quickStartConfig.tableProps.selectableCells;
  readonly customTheme = quickStartConfig.tableProps.customTheme;
}
