// packages/examples/svelte/src/demos/column-visibility/ColumnVisibilityDemo.svelte
<script lang="ts">
  import {SimpleTable} from "@simple-table/svelte";  import type { Theme } from "@simple-table/svelte";
  import MarketingColumnEditorRow from "./MarketingColumnEditorRow.svelte";
  import { columnVisibilityConfig } from "./column-visibility.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();

  const defaultHeaders = columnVisibilityConfig.headers;

  const columnEditorConfig = {
    ...columnVisibilityConfig.tableProps.columnEditorConfig,
    rowRenderer: MarketingColumnEditorRow,
  };
</script>

<SimpleTable
  {defaultHeaders}
  rows={columnVisibilityConfig.rows}
  editColumns={columnVisibilityConfig.tableProps.editColumns}
  editColumnsInitOpen={columnVisibilityConfig.tableProps.editColumnsInitOpen}
  columnEditorConfig={columnEditorConfig}
  {height}
  {theme}
/>

// packages/examples/solid/src/demos/column-visibility/ColumnVisibilityDemo.tsx
import {
  SimpleTable,
  type ColumnVisibilityState,
  type Theme,
} from "@simple-table/solid";
import {
  columnVisibilityConfig,
  getColumnVisibilityDemoHeaders,
  loadColumnVisibilityDemoSaved,
  saveColumnVisibilityDemoState,
} from "./column-visibility.demo-data";
import MarketingColumnEditorRow from "./MarketingColumnEditorRow";
import "@simple-table/solid/styles.css";

export default function ColumnVisibilityDemo(props: { height?: string | number; theme?: Theme }) {
  const headers = () => getColumnVisibilityDemoHeaders(loadColumnVisibilityDemoSaved());

  const onColumnVisibilityChange = (state: ColumnVisibilityState) => {
    saveColumnVisibilityDemoState(state);
  };

  return (
    <SimpleTable
      defaultHeaders={headers()}
      rows={columnVisibilityConfig.rows}
      editColumns
      editColumnsInitOpen
      height={props.height ?? "400px"}
      theme={props.theme}
      onColumnVisibilityChange={onColumnVisibilityChange}
      columnEditorConfig={{
        ...columnVisibilityConfig.tableProps.columnEditorConfig,
        rowRenderer: MarketingColumnEditorRow,
      }}
    />
  );
}
