// packages/examples/solid/src/demos/infinite-scroll/InfiniteScrollDemo.tsx
import { createSignal, createMemo } from "solid-js";
import {SimpleTable} from "@simple-table/solid";import type { Theme, Row } from "@simple-table/solid";
import { infiniteScrollConfig, generateInfiniteScrollData } from "./infinite-scroll.demo-data";
import "@simple-table/solid/styles.css";

const MAX_ROWS = 200;
const BATCH_SIZE = 15;

export default function InfiniteScrollDemo(props: { height?: string | number; theme?: Theme }) {
  const [rows, setRows] = createSignal<Row[]>(generateInfiniteScrollData(0, 30) as Row[]);
  const [loading, setLoading] = createSignal(false);
  const [hasMore, setHasMore] = createSignal(true);

  const statusText = createMemo(() =>
    `${rows().length} rows loaded${hasMore() ? "" : " (all loaded)"}`
  );

  const handleLoadMore = () => {
    if (loading() || !hasMore()) return;
    setLoading(true);
    setTimeout(() => {
      setRows((prev) => {
        const newRows = generateInfiniteScrollData(prev.length, BATCH_SIZE) as Row[];
        const updated = [...prev, ...newRows];
        if (updated.length >= MAX_ROWS) setHasMore(false);
        return updated;
      });
      setLoading(false);
    }, 500);
  };

  return (
    <div>
      <div style={{ "margin-bottom": "8px", "font-size": "13px", color: "#666" }}>
        {statusText()}
      </div>
      <SimpleTable
        defaultHeaders={infiniteScrollConfig.headers}
        rows={rows()}
        onLoadMore={handleLoadMore}
        isLoading={loading()}
        height={props.height ?? "400px"}
        theme={props.theme}
      />
    </div>
  );
}

// packages/examples/vue/src/demos/infinite-scroll/InfiniteScrollDemo.vue
<script setup lang="ts">
import { ref, computed } from "vue";
import {SimpleTable} from "@simple-table/vue";import type { Theme, Row } from "@simple-table/vue";
import { infiniteScrollConfig, generateInfiniteScrollData } from "./infinite-scroll.demo-data";
import "@simple-table/vue/styles.css";

const props = withDefaults(defineProps<{ height?: string | number; theme?: Theme }>(), {
  height: "400px",
});

const MAX_ROWS = 200;
const BATCH_SIZE = 15;

const rows = ref<Row[]>(generateInfiniteScrollData(0, 30) as Row[]);
const loading = ref(false);
const hasMore = ref(true);

const statusText = computed(() =>
  `${rows.value.length} rows loaded${hasMore.value ? "" : " (all loaded)"}`
);

function handleLoadMore() {
  if (loading.value || !hasMore.value) return;
  loading.value = true;
  setTimeout(() => {
    const newRows = generateInfiniteScrollData(rows.value.length, BATCH_SIZE) as Row[];
    rows.value = [...rows.value, ...newRows];
    if (rows.value.length >= MAX_ROWS) hasMore.value = false;
    loading.value = false;
  }, 500);
}
</script>

<template>
  <div>
    <div style="margin-bottom: 8px; font-size: 13px; color: #666">{{ statusText }}</div>
    <SimpleTable
      :default-headers="infiniteScrollConfig.headers"
      :rows="rows"
      :is-loading="loading"
      :on-load-more="handleLoadMore"
      :height="props.height"
      :theme="props.theme"
    />
  </div>
</template>
