// packages/examples/vue/src/demos/header-renderer/HeaderRendererDemo.vue
<script setup lang="ts">
import { ref, computed, defineComponent, h } from "vue";
import { SimpleTable } from "@simple-table/vue";
import type { Theme, VueHeaderObject, Row } from "@simple-table/vue";
import { headerRendererConfig } from "./header-renderer.demo-data";
import "@simple-table/vue/styles.css";

const props = withDefaults(defineProps<{ height?: string | number; theme?: Theme }>(), {
  height: "400px",
});

type SortDir = "asc" | "desc" | null;
const CYCLE: SortDir[] = ["asc", "desc", null];

const sortAccessor = ref<string | null>(null);
const sortDirection = ref<SortDir>(null);

const sortedData = computed(() => {
  if (!sortAccessor.value || !sortDirection.value) return [...headerRendererConfig.rows];
  const acc = sortAccessor.value;
  const dir = sortDirection.value;
  return [...headerRendererConfig.rows].sort((a, b) => {
    const aVal = a[acc];
    const bVal = b[acc];
    if (aVal === bVal) return 0;
    const cmp =
      typeof aVal === "number" && typeof bVal === "number"
        ? aVal - bVal
        : String(aVal).localeCompare(String(bVal));
    return dir === "asc" ? cmp : -cmp;
  });
});

function makeSortableHeader(col: VueHeaderObject) {
  return defineComponent({
    name: `SortHeader-${String(col.accessor)}`,
    setup() {
      return () => {
        const isSorted = sortAccessor.value === col.accessor;
        const dir = isSorted ? sortDirection.value : null;
        const indicator = dir === "asc" ? " ▲" : dir === "desc" ? " ▼" : "";
        const handleClick = () => {
          if (!isSorted) {
            sortAccessor.value = col.accessor as string;
            sortDirection.value = "asc";
            return;
          }
          const idx = CYCLE.indexOf(dir);
          const next = CYCLE[(idx + 1) % CYCLE.length];
          if (next) {
            sortAccessor.value = col.accessor as string;
            sortDirection.value = next;
          } else {
            sortAccessor.value = null;
            sortDirection.value = null;
          }
        };
        return h(
          "div",
          {
            onClick: handleClick,
            style: {
              cursor: "pointer",
              userSelect: "none",
              fontWeight: "600",
              display: "flex",
              alignItems: "center",
              gap: "4px",
            },
          },
          [
            h("span", col.label as string),
            indicator
              ? h("span", { style: { fontSize: "10px", color: "#6366f1" } }, indicator)
              : null,
          ],
        );
      };
    },
  });
}

const headers = computed(() =>
  headerRendererConfig.headers.map((col) => ({
    ...col,
    isSortable: false,
    headerRenderer: makeSortableHeader(col),
  })),
);
</script>

<template>
  <SimpleTable
    :default-headers="headers"
    :rows="sortedData as Row[]"
    :height="props.height"
    :theme="props.theme"
  />
</template>

// packages/examples/react/src/demos/header-renderer/HeaderRendererDemo.tsx
import { useState, useMemo } from "react";
import { SimpleTable } from "@simple-table/react";
import type { Theme, ReactHeaderObject, HeaderRendererProps } from "@simple-table/react";
import { headerRendererConfig } from "./header-renderer.demo-data";
import "@simple-table/react/styles.css";

type SortDir = "asc" | "desc" | null;
interface SortState {
  accessor: string;
  direction: SortDir;
}

const CycleOrder: SortDir[] = ["asc", "desc", null];

const HeaderRendererDemo = ({
  height = "400px",
  theme,
}: {
  height?: string | number;
  theme?: Theme;
}) => {
  const [sortState, setSortState] = useState<SortState | null>(null);

  const sortedData = useMemo(() => {
    if (!sortState || !sortState.direction) return [...headerRendererConfig.rows];
    const { accessor, direction } = sortState;
    return [...headerRendererConfig.rows].sort((a, b) => {
      const aVal = a[accessor];
      const bVal = b[accessor];
      if (aVal === bVal) return 0;
      const cmp =
        typeof aVal === "number" && typeof bVal === "number"
          ? aVal - bVal
          : String(aVal).localeCompare(String(bVal));
      return direction === "asc" ? cmp : -cmp;
    });
  }, [sortState]);

  const headers: ReactHeaderObject[] = useMemo(
    () =>
      headerRendererConfig.headers.map((h) => ({
        ...h,
        isSortable: false,
        headerRenderer: ({ accessor }: HeaderRendererProps) => {
          const isSorted = sortState?.accessor === accessor;
          const dir = isSorted ? sortState!.direction : null;
          const indicator = dir === "asc" ? " ▲" : dir === "desc" ? " ▼" : "";

          const handleClick = () => {
            if (!isSorted) {
              setSortState({ accessor: accessor as string, direction: "asc" });
              return;
            }
            const idx = CycleOrder.indexOf(dir);
            const next = CycleOrder[(idx + 1) % CycleOrder.length];
            setSortState(next ? { accessor: accessor as string, direction: next } : null);
          };

          return (
            <div
              onClick={handleClick}
              style={{
                cursor: "pointer",
                userSelect: "none",
                fontWeight: 600,
                display: "flex",
                alignItems: "center",
                gap: 4,
              }}
            >
              <span>{h.label}</span>
              {indicator && <span style={{ fontSize: 10, color: "#6366f1" }}>{indicator}</span>}
            </div>
          );
        },
      })),
    [sortState],
  );

  return <SimpleTable defaultHeaders={headers} rows={sortedData} height={height} theme={theme} />;
};

export default HeaderRendererDemo;
