// packages/examples/solid/src/demos/header-renderer/HeaderRendererDemo.tsx
import { createSignal, createMemo } from "solid-js";
import {SimpleTable} from "@simple-table/solid";import type { Theme, SolidHeaderObject, HeaderRendererProps } from "@simple-table/solid";
import { headerRendererConfig } from "./header-renderer.demo-data";
import "@simple-table/solid/styles.css";

type SortDir = "asc" | "desc" | null;
const CycleOrder: SortDir[] = ["asc", "desc", null];

export default function HeaderRendererDemo(props: { height?: string | number; theme?: Theme }) {
  const [sortAccessor, setSortAccessor] = createSignal<string | null>(null);
  const [sortDirection, setSortDirection] = createSignal<SortDir>(null);

  const sortedData = createMemo(() => {
    const acc = sortAccessor();
    const dir = sortDirection();
    if (!acc || !dir) return [...headerRendererConfig.rows];
    return [...headerRendererConfig.rows].sort((a, b) => {
      const aVal = a[acc];
      const bVal = b[acc];
      if (aVal === bVal) return 0;
      const cmp = typeof aVal === "number" && typeof bVal === "number"
        ? aVal - bVal
        : String(aVal).localeCompare(String(bVal));
      return dir === "asc" ? cmp : -cmp;
    });
  });

  const headers = createMemo((): SolidHeaderObject[] =>
    headerRendererConfig.headers.map((h) => ({
      ...h,
      isSortable: false,
      headerRenderer: ({ accessor }: HeaderRendererProps) => {
        const isSorted = sortAccessor() === accessor;
        const dir = isSorted ? sortDirection() : null;
        const indicator = dir === "asc" ? " ▲" : dir === "desc" ? " ▼" : "";

        const handleClick = () => {
          if (!isSorted) {
            setSortAccessor(accessor as string);
            setSortDirection("asc");
            return;
          }
          const idx = CycleOrder.indexOf(dir);
          const next = CycleOrder[(idx + 1) % CycleOrder.length];
          setSortAccessor(next ? (accessor as string) : null);
          setSortDirection(next);
        };

        return (
          <div
            onClick={handleClick}
            style={{
              cursor: "pointer",
              "user-select": "none",
              "font-weight": "600",
              display: "flex",
              "align-items": "center",
              gap: "4px",
            }}
          >
            <span>{h.label}</span>
            {indicator && (
              <span style={{ "font-size": "10px", color: "#6366f1" }}>{indicator}</span>
            )}
          </div>
        );
      },
    }))
  );

  return (
    <SimpleTable
      defaultHeaders={headers()}
      rows={sortedData()}
      height={props.height ?? "400px"}
      theme={props.theme}
    />
  );
}

// packages/examples/react/src/demos/header-renderer/HeaderRendererDemo.tsx
import { useState, useMemo } from "react";
import { SimpleTable } from "@simple-table/react";
import type { Theme, ReactHeaderObject, HeaderRendererProps } from "@simple-table/react";
import { headerRendererConfig } from "./header-renderer.demo-data";
import "@simple-table/react/styles.css";

type SortDir = "asc" | "desc" | null;
interface SortState {
  accessor: string;
  direction: SortDir;
}

const CycleOrder: SortDir[] = ["asc", "desc", null];

const HeaderRendererDemo = ({
  height = "400px",
  theme,
}: {
  height?: string | number;
  theme?: Theme;
}) => {
  const [sortState, setSortState] = useState<SortState | null>(null);

  const sortedData = useMemo(() => {
    if (!sortState || !sortState.direction) return [...headerRendererConfig.rows];
    const { accessor, direction } = sortState;
    return [...headerRendererConfig.rows].sort((a, b) => {
      const aVal = a[accessor];
      const bVal = b[accessor];
      if (aVal === bVal) return 0;
      const cmp =
        typeof aVal === "number" && typeof bVal === "number"
          ? aVal - bVal
          : String(aVal).localeCompare(String(bVal));
      return direction === "asc" ? cmp : -cmp;
    });
  }, [sortState]);

  const headers: ReactHeaderObject[] = useMemo(
    () =>
      headerRendererConfig.headers.map((h) => ({
        ...h,
        isSortable: false,
        headerRenderer: ({ accessor }: HeaderRendererProps) => {
          const isSorted = sortState?.accessor === accessor;
          const dir = isSorted ? sortState!.direction : null;
          const indicator = dir === "asc" ? " ▲" : dir === "desc" ? " ▼" : "";

          const handleClick = () => {
            if (!isSorted) {
              setSortState({ accessor: accessor as string, direction: "asc" });
              return;
            }
            const idx = CycleOrder.indexOf(dir);
            const next = CycleOrder[(idx + 1) % CycleOrder.length];
            setSortState(next ? { accessor: accessor as string, direction: next } : null);
          };

          return (
            <div
              onClick={handleClick}
              style={{
                cursor: "pointer",
                userSelect: "none",
                fontWeight: 600,
                display: "flex",
                alignItems: "center",
                gap: 4,
              }}
            >
              <span>{h.label}</span>
              {indicator && <span style={{ fontSize: 10, color: "#6366f1" }}>{indicator}</span>}
            </div>
          );
        },
      })),
    [sortState],
  );

  return <SimpleTable defaultHeaders={headers} rows={sortedData} height={height} theme={theme} />;
};

export default HeaderRendererDemo;
