// packages/examples/svelte/src/demos/single-row-children/SingleRowChildrenDemo.svelte
<script lang="ts">
  import {SimpleTable} from "@simple-table/svelte";  import type { Theme } from "@simple-table/svelte";
  import { singleRowChildrenConfig } from "./single-row-children.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
</script>

<SimpleTable
  defaultHeaders={singleRowChildrenConfig.headers}
  rows={singleRowChildrenConfig.rows}
  columnResizing={singleRowChildrenConfig.tableProps.columnResizing}
  selectableCells={singleRowChildrenConfig.tableProps.selectableCells}
  {height}
  {theme}
/>

// packages/examples/vue/src/demos/single-row-children/SingleRowChildrenDemo.vue
<template>
  <SimpleTable
    :default-headers="singleRowChildrenConfig.headers"
    :rows="singleRowChildrenConfig.rows"
    :column-resizing="singleRowChildrenConfig.tableProps.columnResizing"
    :selectable-cells="singleRowChildrenConfig.tableProps.selectableCells"
    :height="height"
    :theme="theme"
  />
</template>

<script setup lang="ts">
import {SimpleTable} from "@simple-table/vue";import type { Theme } from "@simple-table/vue";
import { singleRowChildrenConfig } from "./single-row-children.demo-data";
import "@simple-table/vue/styles.css";

withDefaults(defineProps<{ height?: string | number; theme?: Theme }>(), { height: "400px" });
</script>
