// packages/examples/svelte/src/demos/charts/ChartsDemo.svelte
<script lang="ts">
  import {SimpleTable} from "@simple-table/svelte";  import type { Theme } from "@simple-table/svelte";
  import { chartsConfig } from "./charts.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
</script>

<SimpleTable
  columnReordering={chartsConfig.tableProps.columnReordering}
  columnResizing={chartsConfig.tableProps.columnResizing}
  defaultHeaders={chartsConfig.headers}
  rows={chartsConfig.rows}
  selectableCells={chartsConfig.tableProps.selectableCells}
  {height}
  {theme}
/>

// packages/examples/angular/src/demos/charts/charts-demo.component.ts
import { Component, Input } from "@angular/core";
import {SimpleTableComponent} from "@simple-table/angular";import type { AngularHeaderObject, Row, Theme } from "@simple-table/angular";
import { chartsConfig } from "./charts.demo-data";
import "@simple-table/angular/styles.css";

@Component({
  selector: "charts-demo",
  standalone: true,
  imports: [SimpleTableComponent],
  template: `
    <simple-table
      [columnReordering]="true"
      [columnResizing]="true"
      [defaultHeaders]="headers"
      [rows]="rows"
      [selectableCells]="true"
      [height]="height"
      [theme]="theme"
    ></simple-table>
  `,
})
export class ChartsDemoComponent {
  @Input() height: string | number = "400px";
  @Input() theme?: Theme;

  readonly headers: AngularHeaderObject[] = chartsConfig.headers;
  readonly rows: Row[] = chartsConfig.rows;
}
