// packages/examples/react/src/demos/custom-theme/CustomThemeDemo.tsx
import {SimpleTable} from "@simple-table/react";import type { Theme } from "@simple-table/react";
import { customThemeConfig } from "./custom-theme.demo-data";
import "@simple-table/react/styles.css";
import "./custom-theme.css";

const CustomThemeDemo = ({
  height = "400px",
  theme,
}: {
  height?: string | number;
  theme?: Theme;
}) => {
  return (
    <SimpleTable
      defaultHeaders={customThemeConfig.headers}
      rows={customThemeConfig.rows}
      theme={theme ?? "custom"}
      customTheme={customThemeConfig.tableProps.customTheme}
      columnResizing
      selectableCells
      height={height}
    />
  );
};

export default CustomThemeDemo;

// packages/examples/svelte/src/demos/custom-theme/CustomThemeDemo.svelte
<script lang="ts">
  import {SimpleTable} from "@simple-table/svelte";  import type { Theme } from "@simple-table/svelte";
  import { customThemeConfig } from "./custom-theme.demo-data";
  import "@simple-table/svelte/styles.css";
  import "./custom-theme.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
</script>

<SimpleTable
  defaultHeaders={customThemeConfig.headers}
  rows={customThemeConfig.rows}
  theme={theme ?? "custom"}
  customTheme={customThemeConfig.tableProps.customTheme}
  columnResizing={true}
  selectableCells={true}
  {height}
/>
