// packages/examples/vue/src/demos/custom-theme/CustomThemeDemo.vue
<script setup lang="ts">
import {SimpleTable} from "@simple-table/vue";import type { Theme } from "@simple-table/vue";
import { customThemeConfig } from "./custom-theme.demo-data";
import "@simple-table/vue/styles.css";
import "./custom-theme.css";

const props = withDefaults(defineProps<{ height?: string | number; theme?: Theme }>(), {
  height: "400px",
});
</script>

<template>
  <SimpleTable
    :default-headers="customThemeConfig.headers"
    :rows="customThemeConfig.rows"
    :theme="props.theme ?? 'custom'"
    :custom-theme="customThemeConfig.tableProps.customTheme"
    :column-resizing="true"
    :selectable-cells="true"
    :height="props.height"
  />
</template>

// packages/examples/svelte/src/demos/custom-theme/CustomThemeDemo.svelte
<script lang="ts">
  import {SimpleTable} from "@simple-table/svelte";  import type { Theme } from "@simple-table/svelte";
  import { customThemeConfig } from "./custom-theme.demo-data";
  import "@simple-table/svelte/styles.css";
  import "./custom-theme.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
</script>

<SimpleTable
  defaultHeaders={customThemeConfig.headers}
  rows={customThemeConfig.rows}
  theme={theme ?? "custom"}
  customTheme={customThemeConfig.tableProps.customTheme}
  columnResizing={true}
  selectableCells={true}
  {height}
/>
