// packages/examples/solid/src/demos/nested-tables/NestedTablesDemo.tsx
import { createMemo } from "solid-js";
import {SimpleTable} from "@simple-table/solid";import type { Theme } from "@simple-table/solid";
import { nestedTablesConfig, generateNestedTablesData } from "./nested-tables.demo-data";
import "@simple-table/solid/styles.css";

export default function NestedTablesDemo(props: { height?: string | number; theme?: Theme }) {
  const sampleData = createMemo(() => generateNestedTablesData(25));

  return (
    <SimpleTable
      autoExpandColumns={nestedTablesConfig.tableProps.autoExpandColumns}
      defaultHeaders={nestedTablesConfig.headers}
      rows={sampleData()}
      rowGrouping={nestedTablesConfig.tableProps.rowGrouping}
      getRowId={nestedTablesConfig.tableProps.getRowId}
      expandAll={nestedTablesConfig.tableProps.expandAll}
      columnResizing={nestedTablesConfig.tableProps.columnResizing}
      height={props.height ?? "500px"}
      theme={props.theme}
    />
  );
}

// packages/examples/vue/src/demos/nested-tables/NestedTablesDemo.vue
<template>
  <SimpleTable
    :auto-expand-columns="nestedTablesConfig.tableProps.autoExpandColumns"
    :default-headers="nestedTablesConfig.headers"
    :rows="sampleData"
    :row-grouping="nestedTablesConfig.tableProps.rowGrouping"
    :get-row-id="nestedTablesConfig.tableProps.getRowId"
    :expand-all="nestedTablesConfig.tableProps.expandAll"
    :column-resizing="nestedTablesConfig.tableProps.columnResizing"
    :height="height"
    :theme="theme"
  />
</template>

<script setup lang="ts">
import { computed } from "vue";
import {SimpleTable} from "@simple-table/vue";import type { Theme } from "@simple-table/vue";
import { nestedTablesConfig, generateNestedTablesData } from "./nested-tables.demo-data";
import "@simple-table/vue/styles.css";

withDefaults(defineProps<{ height?: string | number; theme?: Theme }>(), { height: "500px" });

const sampleData = computed(() => generateNestedTablesData(25));
</script>
