// packages/examples/angular/src/demos/tooltip/tooltip-demo.component.ts
import { Component, Input } from "@angular/core";
import {SimpleTableComponent} from "@simple-table/angular";import type { AngularHeaderObject, Row, Theme } from "@simple-table/angular";
import { tooltipConfig } from "./tooltip.demo-data";
import "@simple-table/angular/styles.css";

@Component({
  selector: "tooltip-demo",
  standalone: true,
  imports: [SimpleTableComponent],
  template: `
    <simple-table
      [rows]="rows"
      [defaultHeaders]="headers"
      [height]="height"
      [theme]="theme"
      [columnResizing]="true"
      [columnReordering]="true"
      [selectableCells]="true"
    ></simple-table>
  `,
})
export class TooltipDemoComponent {
  @Input() height: string | number = "400px";
  @Input() theme?: Theme;

  readonly rows: Row[] = tooltipConfig.rows;
  readonly headers: AngularHeaderObject[] = tooltipConfig.headers;
}

// packages/examples/solid/src/demos/tooltip/TooltipDemo.tsx
import {SimpleTable} from "@simple-table/solid";import type { Theme } from "@simple-table/solid";
import { tooltipConfig } from "./tooltip.demo-data";
import "@simple-table/solid/styles.css";

export default function TooltipDemo(props: { height?: string | number; theme?: Theme }) {
  return (
    <SimpleTable
      defaultHeaders={tooltipConfig.headers}
      rows={tooltipConfig.rows}
      height={props.height ?? "400px"}
      theme={props.theme}
      columnResizing={tooltipConfig.tableProps.columnResizing}
      columnReordering={tooltipConfig.tableProps.columnReordering}
      selectableCells={tooltipConfig.tableProps.selectableCells}
    />
  );
}
