// packages/examples/angular/src/demos/column-resizing/column-resizing-demo.component.ts
import { NgIf } from "@angular/common";
import { Component, Input, OnInit } from "@angular/core";
import { SimpleTableComponent } from "@simple-table/angular";
import type { AngularHeaderObject, Row, Theme } from "@simple-table/angular";
import { columnResizingHeaders, columnResizingData, COLUMN_RESIZING_STORAGE_KEY } from "./column-resizing.demo-data";
import "@simple-table/angular/styles.css";

@Component({
  selector: "column-resizing-demo",
  standalone: true,
  imports: [SimpleTableComponent, NgIf],
  template: `
    <div style="position: relative; height: 100%">
      <div
        *ngIf="saveMessage"
        style="position: absolute; top: 8px; right: 8px; background: #10b981; color: white; padding: 8px 16px; border-radius: 6px; font-size: 14px; font-weight: 500; z-index: 1000; box-shadow: 0 2px 8px rgba(0,0,0,0.15);"
      >
        {{ saveMessage }}
      </div>
      <simple-table
        [columnResizing]="true"
        [rows]="rows"
        [defaultHeaders]="headers"
        [height]="height"
        [theme]="theme"
        [onColumnWidthChange]="handleColumnWidthChange"
      ></simple-table>
    </div>
  `,
})
export class ColumnResizingDemoComponent implements OnInit {
  @Input() height: string | number = "400px";
  @Input() theme?: Theme;

  readonly rows: Row[] = columnResizingData;
  headers: AngularHeaderObject[] = [...columnResizingHeaders];
  saveMessage = "";

  handleColumnWidthChange = (updatedHeaders: AngularHeaderObject[]) => {
    try {
      const widthMap: Record<string, unknown> = {};
      for (const h of updatedHeaders) widthMap[h.accessor] = h.width;
      localStorage.setItem(COLUMN_RESIZING_STORAGE_KEY, JSON.stringify(widthMap));
      this.headers = updatedHeaders;
      this.saveMessage = "Column widths saved!";
      setTimeout(() => { this.saveMessage = ""; }, 2000);
    } catch {
      this.saveMessage = "Failed to save widths";
      setTimeout(() => { this.saveMessage = ""; }, 2000);
    }
  };

  ngOnInit() {
    try {
      const saved = localStorage.getItem(COLUMN_RESIZING_STORAGE_KEY);
      if (saved) {
        const widthMap = JSON.parse(saved) as Record<string, number | string | undefined>;
        this.headers = columnResizingHeaders.map((h) => ({
          ...h,
          width: widthMap[h.accessor] ?? h.width,
        }));
      }
    } catch { /* ignore */ }
  }
}

// packages/examples/solid/src/demos/column-resizing/ColumnResizingDemo.tsx
import { createSignal, onMount, onCleanup } from "solid-js";
import { SimpleTable } from "@simple-table/solid";
import type { Theme, SolidHeaderObject } from "@simple-table/solid";
import { columnResizingHeaders, columnResizingData, COLUMN_RESIZING_STORAGE_KEY } from "./column-resizing.demo-data";
import "@simple-table/solid/styles.css";

export default function ColumnResizingDemo(props: { height?: string | number; theme?: Theme }) {
  const [headers, setHeaders] = createSignal([...columnResizingHeaders]);
  const [saveMessage, setSaveMessage] = createSignal("");

  let messageTimer: ReturnType<typeof setTimeout> | undefined;

  const clearMessageTimer = () => {
    if (messageTimer !== undefined) {
      clearTimeout(messageTimer);
      messageTimer = undefined;
    }
  };

  onMount(() => {
    try {
      const saved = localStorage.getItem(COLUMN_RESIZING_STORAGE_KEY);
      if (saved) {
        const widthMap = JSON.parse(saved) as Record<string, number | string | undefined>;
        setHeaders(
          columnResizingHeaders.map((h) => ({ ...h, width: widthMap[h.accessor] ?? h.width })),
        );
      }
    } catch {
      /* ignore */
    }
  });

  onCleanup(() => {
    clearMessageTimer();
  });

  const handleColumnWidthChange = (updatedHeaders: SolidHeaderObject[]) => {
    try {
      const widthMap: Record<string, unknown> = {};
      for (const h of updatedHeaders) widthMap[h.accessor] = h.width;
      localStorage.setItem(COLUMN_RESIZING_STORAGE_KEY, JSON.stringify(widthMap));
      setHeaders(updatedHeaders);
      setSaveMessage("Column widths saved!");
      clearMessageTimer();
      messageTimer = setTimeout(() => setSaveMessage(""), 2000);
    } catch {
      setSaveMessage("Failed to save widths");
      clearMessageTimer();
      messageTimer = setTimeout(() => setSaveMessage(""), 2000);
    }
  };

  return (
    <div style={{ position: "relative", height: "100%" }}>
      {saveMessage() && (
        <div
          style={{
            position: "absolute",
            top: "8px",
            right: "8px",
            background: "#10b981",
            color: "white",
            padding: "8px 16px",
            "border-radius": "6px",
            "font-size": "14px",
            "font-weight": "500",
            "z-index": 1000,
            "box-shadow": "0 2px 8px rgba(0,0,0,0.15)",
          }}
        >
          {saveMessage()}
        </div>
      )}
      <SimpleTable
        columnResizing
        defaultHeaders={headers()}
        rows={columnResizingData}
        height={props.height ?? "400px"}
        theme={props.theme}
        onColumnWidthChange={handleColumnWidthChange}
      />
    </div>
  );
}
