// packages/examples/angular/src/demos/column-alignment/column-alignment-demo.component.ts
import { Component, Input } from "@angular/core";
import {SimpleTableComponent} from "@simple-table/angular";import type { AngularHeaderObject, Row, Theme } from "@simple-table/angular";
import { columnAlignmentConfig } from "./column-alignment.demo-data";
import "@simple-table/angular/styles.css";

@Component({
  selector: "column-alignment-demo",
  standalone: true,
  imports: [SimpleTableComponent],
  template: `
    <simple-table
      [rows]="rows"
      [defaultHeaders]="headers"
      [height]="height"
      [theme]="theme"
    ></simple-table>
  `,
})
export class ColumnAlignmentDemoComponent {
  @Input() height: string | number = "400px";
  @Input() theme?: Theme;

  readonly rows: Row[] = columnAlignmentConfig.rows;
  readonly headers: AngularHeaderObject[] = columnAlignmentConfig.headers;
}

// packages/examples/solid/src/demos/column-alignment/ColumnAlignmentDemo.tsx
import {SimpleTable} from "@simple-table/solid";import type { Theme } from "@simple-table/solid";
import { columnAlignmentConfig } from "./column-alignment.demo-data";
import "@simple-table/solid/styles.css";

export default function ColumnAlignmentDemo(props: { height?: string | number; theme?: Theme }) {
  return (
    <SimpleTable
      defaultHeaders={columnAlignmentConfig.headers}
      rows={columnAlignmentConfig.rows}
      height={props.height ?? "400px"}
      theme={props.theme}
    />
  );
}
