// packages/examples/vue/src/demos/column-alignment/ColumnAlignmentDemo.vue
<template>
  <SimpleTable
    :default-headers="columnAlignmentConfig.headers"
    :rows="columnAlignmentConfig.rows"
    :height="height"
    :theme="theme"
  />
</template>

<script setup lang="ts">
import {SimpleTable} from "@simple-table/vue";import type { Theme } from "@simple-table/vue";
import { columnAlignmentConfig } from "./column-alignment.demo-data";
import "@simple-table/vue/styles.css";

withDefaults(defineProps<{ height?: string | number; theme?: Theme }>(), {
  height: "400px",
});
</script>

// packages/examples/solid/src/demos/column-alignment/ColumnAlignmentDemo.tsx
import {SimpleTable} from "@simple-table/solid";import type { Theme } from "@simple-table/solid";
import { columnAlignmentConfig } from "./column-alignment.demo-data";
import "@simple-table/solid/styles.css";

export default function ColumnAlignmentDemo(props: { height?: string | number; theme?: Theme }) {
  return (
    <SimpleTable
      defaultHeaders={columnAlignmentConfig.headers}
      rows={columnAlignmentConfig.rows}
      height={props.height ?? "400px"}
      theme={props.theme}
    />
  );
}
