// packages/examples/angular/src/demos/crm/crm-contact-now-cell.component.ts
import { Component } from "@angular/core";
import { crmCellPalette } from "./crm-demo-context";

@Component({
  standalone: true,
  selector: "demo-crm-contact-now",
  template: `
    <a
      href="#"
      style="cursor:pointer;font-size:0.875rem;text-decoration:none;font-weight:600;"
      [style.color]="palette().link"
      (click)="$event.preventDefault()"
      >Contact Now</a>
  `,
})
export class CrmContactNowCellComponent {
  protected readonly palette = crmCellPalette;
}

// packages/examples/svelte/src/demos/crm/CrmContactNowCell.svelte
<script lang="ts">
  import type { CellRendererProps } from "@simple-table/svelte";
  import { crmCellColors } from "./crm-demo-stores";

  let _p: CellRendererProps = $props();
  const colors = $derived($crmCellColors);
</script>

<!-- svelte-ignore a11y_invalid_attribute -->
<a
  href="#"
  style="cursor:pointer;font-size:0.875rem;color:{colors.link};text-decoration:none;font-weight:600;"
  onclick={(e) => e.preventDefault()}>Contact Now</a>
