// packages/examples/angular/src/demos/crm/crm-list-cell.component.ts
import { Component, Input } from "@angular/core";
import type { Row } from "@simple-table/angular";
import type { CRMLead } from "./crm.demo-data";
import { crmCellPalette } from "./crm-demo-context";

@Component({
  standalone: true,
  selector: "demo-crm-list",
  template: `
    <a
      href="#"
      style="cursor:pointer;font-size:0.875rem;text-decoration:none;font-weight:600;"
      [style.color]="palette().link"
      (click)="$event.preventDefault()"
      >{{ d.list }}</a>
  `,
})
export class CrmListCellComponent {
  @Input({ required: true }) row!: Row;

  protected readonly palette = crmCellPalette;

  get d(): CRMLead {
    return this.row as unknown as CRMLead;
  }
}

// packages/examples/svelte/src/demos/crm/CrmListCell.svelte
<script lang="ts">
  import type { CellRendererProps } from "@simple-table/svelte";
  import type { CRMLead } from "./crm.demo-data";
  import { crmCellColors } from "./crm-demo-stores";

  let { row }: CellRendererProps = $props();
  const d = $derived(row as unknown as CRMLead);
  const colors = $derived($crmCellColors);
</script>

<!-- svelte-ignore a11y_invalid_attribute -->
<a
  href="#"
  style="cursor:pointer;font-size:0.875rem;color:{colors.link};text-decoration:none;font-weight:600;"
  onclick={(e) => e.preventDefault()}>{d.list}</a>
