// packages/examples/svelte/src/demos/value-formatter/ValueFormatterDemo.svelte
<script lang="ts">
  import {SimpleTable} from "@simple-table/svelte";  import type { Theme } from "@simple-table/svelte";
  import { valueFormatterConfig } from "./value-formatter.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
</script>

<SimpleTable
  defaultHeaders={valueFormatterConfig.headers}
  rows={valueFormatterConfig.rows}
  {height}
  {theme}
  selectableCells={valueFormatterConfig.tableProps.selectableCells}
/>

// packages/examples/vue/src/demos/value-formatter/ValueFormatterDemo.vue
<template>
  <SimpleTable
    :default-headers="valueFormatterConfig.headers"
    :rows="valueFormatterConfig.rows"
    :height="height"
    :theme="theme"
    :selectable-cells="valueFormatterConfig.tableProps.selectableCells"
  />
</template>

<script setup lang="ts">
import {SimpleTable} from "@simple-table/vue";import type { Theme } from "@simple-table/vue";
import { valueFormatterConfig } from "./value-formatter.demo-data";
import "@simple-table/vue/styles.css";

withDefaults(defineProps<{ height?: string | number; theme?: Theme }>(), {
  height: "400px",
});
</script>
