// packages/examples/angular/src/demos/csv-export/csv-export-demo.component.ts
import { Component, Input, ViewChild } from "@angular/core";
import {SimpleTableComponent} from "@simple-table/angular";import type { AngularHeaderObject, Row, Theme } from "@simple-table/angular";
import { csvExportHeaders, csvExportData, csvExportConfig } from "./csv-export.demo-data";
import "@simple-table/angular/styles.css";

@Component({
  selector: "csv-export-demo",
  standalone: true,
  imports: [SimpleTableComponent],
  template: `
    <div>
      <div style="display: flex; gap: 8px; margin-bottom: 12px">
        <button style="padding: 6px 16px" (click)="handleExport()">Export to CSV</button>
        <button style="padding: 6px 16px" (click)="handleGetInfo()">Get Table Info</button>
      </div>
      <simple-table
        #simpleTable
        [rows]="rows"
        [defaultHeaders]="headers"
        [editColumns]="true"
        [selectableCells]="true"
        [customTheme]="{ rowHeight: 32 }"
        [height]="height"
        [theme]="theme"
      ></simple-table>
    </div>
  `,
})
export class CsvExportDemoComponent {
  @ViewChild("simpleTable") tableRef!: SimpleTableComponent;
  @Input() height: string | number = "400px";
  @Input() theme?: Theme;

  readonly rows: Row[] = csvExportData;
  readonly headers: AngularHeaderObject[] = csvExportHeaders.map((h) => {
    if (h.accessor === "actions") {
      return {
        ...h,
        cellRenderer: () =>
          `<button style="background:#3b82f6;color:white;border:none;padding:4px 12px;border-radius:4px;cursor:pointer;font-size:12px;font-weight:bold">View</button>`,
      };
    }
    return { ...h };
  });

  handleExport(): void {
    this.tableRef.getAPI()?.exportToCSV();
  }

  handleGetInfo(): void {
    const api = this.tableRef.getAPI();
    if (!api) return;
    const rows = api.getAllRows();
    const hdrs = api.getHeaders();
    const totalRevenue = rows.reduce((sum, r) => sum + (Number((r.row as { revenue?: unknown }).revenue) || 0), 0);
    alert(
      `Table Info:\n• ${rows.length} rows\n• ${hdrs.length} columns\n• Columns: ${hdrs.map((h) => h.label).join(", ")}\n• Total Revenue: $${totalRevenue.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
    );
  }
}

// packages/examples/react/src/demos/csv-export/CsvExportDemo.tsx
import { useRef, useMemo } from "react";
import { SimpleTable } from "@simple-table/react";
import type { Theme, TableAPI, ReactHeaderObject } from "@simple-table/react";
import { csvExportHeaders, csvExportData, csvExportConfig } from "./csv-export.demo-data";
import "@simple-table/react/styles.css";

const CsvExportDemo = ({
  height = "400px",
  theme,
}: {
  height?: string | number;
  theme?: Theme;
}) => {
  const tableRef = useRef<TableAPI>(null);

  const headers: ReactHeaderObject[] = useMemo(
    () =>
      csvExportHeaders.map((h) => {
        if (h.accessor === "actions") {
          return {
            ...h,
            cellRenderer: () => (
              <button
                style={{
                  backgroundColor: "#3b82f6",
                  color: "white",
                  border: "none",
                  padding: "4px 12px",
                  borderRadius: 4,
                  cursor: "pointer",
                  fontSize: 12,
                  fontWeight: "bold",
                }}
              >
                View
              </button>
            ),
          };
        }
        return h;
      }),
    [],
  );

  const handleExport = () => {
    tableRef.current?.exportToCSV();
  };

  const handleGetInfo = () => {
    const api = tableRef.current;
    if (!api) return;
    const rows = api.getAllRows();
    const hdrs = api.getHeaders();
    const totalRevenue = rows.reduce((sum, r) => {
      const row = r as Record<string, unknown>;
      return sum + (Number(row.revenue) || 0);
    }, 0);
    alert(
      `Table Info:\n• ${rows.length} rows\n• ${hdrs.length} columns\n• Columns: ${hdrs.map((h) => h.label).join(", ")}\n• Total Revenue: $${totalRevenue.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
    );
  };

  return (
    <div>
      <div style={{ marginBottom: 12, display: "flex", gap: 8 }}>
        <button onClick={handleExport} style={{ padding: "6px 16px" }}>
          Export to CSV
        </button>
        <button onClick={handleGetInfo} style={{ padding: "6px 16px" }}>
          Get Table Info
        </button>
      </div>
      <SimpleTable
        ref={tableRef}
        defaultHeaders={headers}
        rows={csvExportData}
        editColumns={csvExportConfig.tableProps.editColumns}
        selectableCells={csvExportConfig.tableProps.selectableCells}
        customTheme={csvExportConfig.tableProps.customTheme}
        height={height}
        theme={theme}
      />
    </div>
  );
};

export default CsvExportDemo;
