// packages/examples/svelte/src/demos/column-width/ColumnWidthDemo.svelte
<script lang="ts">
  import {SimpleTable} from "@simple-table/svelte";  import type { Theme } from "@simple-table/svelte";
  import { columnWidthConfig } from "./column-width.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
  let isMobile = $state(false);

  function checkMobile() {
    isMobile = window.innerWidth < 768;
  }

  $effect(() => {
    checkMobile();
    window.addEventListener("resize", checkMobile);
    return () => window.removeEventListener("resize", checkMobile);
  });
</script>

<SimpleTable
  autoExpandColumns={!isMobile}
  columnResizing={true}
  defaultHeaders={columnWidthConfig.headers}
  rows={columnWidthConfig.rows}
  {height}
  {theme}
/>

// packages/examples/solid/src/demos/column-width/ColumnWidthDemo.tsx
import { createSignal, onMount, onCleanup } from "solid-js";
import {SimpleTable} from "@simple-table/solid";import type { Theme } from "@simple-table/solid";
import { columnWidthConfig } from "./column-width.demo-data";
import "@simple-table/solid/styles.css";

export default function ColumnWidthDemo(props: { height?: string | number; theme?: Theme }) {
  const [isMobile, setIsMobile] = createSignal(false);

  const check = () => setIsMobile(window.innerWidth < 768);

  onMount(() => {
    check();
    window.addEventListener("resize", check);
  });

  onCleanup(() => {
    window.removeEventListener("resize", check);
  });

  return (
    <SimpleTable
      autoExpandColumns={!isMobile()}
      columnResizing
      defaultHeaders={columnWidthConfig.headers}
      height={props.height ?? "400px"}
      rows={columnWidthConfig.rows}
      theme={props.theme}
    />
  );
}
