// packages/examples/svelte/src/demos/charts/ChartsDemo.svelte
<script lang="ts">
  import {SimpleTable} from "@simple-table/svelte";  import type { Theme } from "@simple-table/svelte";
  import { chartsConfig } from "./charts.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
</script>

<SimpleTable
  columnReordering={chartsConfig.tableProps.columnReordering}
  columnResizing={chartsConfig.tableProps.columnResizing}
  defaultHeaders={chartsConfig.headers}
  rows={chartsConfig.rows}
  selectableCells={chartsConfig.tableProps.selectableCells}
  {height}
  {theme}
/>

// packages/examples/vue/src/demos/charts/ChartsDemo.vue
<template>
  <SimpleTable
    :column-reordering="chartsConfig.tableProps.columnReordering"
    :column-resizing="chartsConfig.tableProps.columnResizing"
    :default-headers="chartsConfig.headers"
    :rows="chartsConfig.rows"
    :selectable-cells="chartsConfig.tableProps.selectableCells"
    :height="height"
    :theme="theme"
  />
</template>

<script setup lang="ts">
import {SimpleTable} from "@simple-table/vue";import type { Theme } from "@simple-table/vue";
import { chartsConfig } from "./charts.demo-data";
import "@simple-table/vue/styles.css";

withDefaults(defineProps<{ height?: string | number; theme?: Theme }>(), { height: "400px" });
</script>
