// packages/examples/angular/src/demos/programmatic-control/programmatic-control-demo.component.ts
import { Component, Input, ViewChild } from "@angular/core";
import {SimpleTableComponent} from "@simple-table/angular";import type { AngularHeaderObject, Row, Theme } from "@simple-table/angular";
import { programmaticControlConfig, PROGRAMMATIC_CONTROL_STATUS_COLORS } from "./programmatic-control.demo-data";
import "@simple-table/angular/styles.css";

@Component({
  selector: "programmatic-control-demo",
  standalone: true,
  imports: [SimpleTableComponent],
  template: `
    <div>
      <div style="margin-bottom: 12px; padding: 8px 12px; background-color: #eff6ff; border: 1px solid #bfdbfe; border-radius: 6px; color: #1e40af; font-size: 14px">
        {{ statusMessage }}
      </div>
      <div style="margin-bottom: 12px; display: flex; gap: 8px; flex-wrap: wrap">
        <button (click)="sortByName()">Sort by Name (A-Z)</button>
        <button (click)="sortByPrice()">Sort by Price (High to Low)</button>
        <button (click)="filterAvailable()">Filter: Available</button>
        <button (click)="clearFilters()">Clear Filters</button>
        <button (click)="getInfo()">Get Table Info</button>
      </div>
      <simple-table
        #simpleTable
        [rows]="rows"
        [defaultHeaders]="headers"
        [height]="height"
        [theme]="theme"
      ></simple-table>
    </div>
  `,
})
export class ProgrammaticControlDemoComponent {
  @ViewChild("simpleTable") tableRef!: SimpleTableComponent;
  @Input() height: string | number = "400px";
  @Input() theme?: Theme;

  statusMessage = "No status message";
  readonly rows: Row[] = programmaticControlConfig.rows;
  readonly headers: AngularHeaderObject[] = programmaticControlConfig.headers.map((h) => {
    if (h.accessor === "status") {
      return {
        ...h,
        cellRenderer: ({ row }: { row: Record<string, unknown> }) => {
          const s = String(row.status);
          const colors = PROGRAMMATIC_CONTROL_STATUS_COLORS[s] ?? { bg: "#f3f4f6", color: "#374151" };
          return `<span style="background:${colors.bg};color:${colors.color};padding:4px 8px;border-radius:4px;font-size:12px;font-weight:bold">${s}</span>`;
        },
      };
    }
    return { ...h };
  });

  sortByName(): void {
    this.tableRef.getAPI()?.applySortState({ accessor: "name", direction: "asc" });
    this.statusMessage = "Sorted by Name (A-Z)";
  }

  sortByPrice(): void {
    this.tableRef.getAPI()?.applySortState({ accessor: "price", direction: "desc" });
    this.statusMessage = "Sorted by Price (High to Low)";
  }

  filterAvailable(): void {
    this.tableRef.getAPI()?.applyFilter({ accessor: "status", operator: "equals", value: "Available" });
    this.statusMessage = "Filtered to show only Available products";
  }

  clearFilters(): void {
    this.tableRef.getAPI()?.clearAllFilters();
    this.statusMessage = "All filters cleared";
  }

  getInfo(): void {
    const api = this.tableRef.getAPI();
    if (!api) return;
    const allRows = api.getAllRows();
    const hdrs = api.getHeaders();
    const sortState = api.getSortState();
    const filterState = api.getFilterState();
    const totalValue = allRows.reduce((sum, r) => {
      const data = r.row as { price?: number; stock?: number };
      return sum + (Number(data.price) || 0) * (Number(data.stock) || 0);
    }, 0);
    const sortInfo = sortState ? `${sortState.key.label} (${sortState.direction})` : "None";
    alert(
      `Table Info:\n• Rows: ${allRows.length}\n• Columns: ${hdrs.length}\n• Active filters: ${Object.keys(filterState).length}\n• Sort: ${sortInfo}\n• Total inventory value: $${totalValue.toFixed(2)}`,
    );
    this.statusMessage = "Table info displayed";
  }
}

// packages/examples/svelte/src/demos/programmatic-control/ProgrammaticControlDemo.svelte
<script lang="ts">
  import { SimpleTable } from "@simple-table/svelte";
  import type { Theme, SvelteHeaderObject } from "@simple-table/svelte";
  import { programmaticControlConfig, PROGRAMMATIC_CONTROL_STATUS_COLORS } from "./programmatic-control.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();

  let tableRef: any;
  let statusMessage = $state("No status message");

  const headers: SvelteHeaderObject[] = programmaticControlConfig.headers.map((h) => {
    if (h.accessor === "status") {
      return {
        ...h,
        cellRenderer: ({ row }: { row: Record<string, unknown> }) => {
          const s = String(row.status);
          const colors = PROGRAMMATIC_CONTROL_STATUS_COLORS[s] ?? { bg: "#f3f4f6", color: "#374151" };
          return `<span style="background:${colors.bg};color:${colors.color};padding:4px 8px;border-radius:4px;font-size:12px;font-weight:bold">${s}</span>`;
        },
      };
    }
    return { ...h };
  });

  function handleSortByName() {
    tableRef?.getAPI()?.applySortState({ accessor: "name", direction: "asc" });
    statusMessage = "Sorted by Name (A-Z)";
  }

  function handleSortByPrice() {
    tableRef?.getAPI()?.applySortState({ accessor: "price", direction: "desc" });
    statusMessage = "Sorted by Price (High to Low)";
  }

  function handleFilterAvailable() {
    tableRef?.getAPI()?.applyFilter({ accessor: "status", operator: "equals", value: "Available" });
    statusMessage = "Filtered to show only Available products";
  }

  function handleClearFilters() {
    tableRef?.getAPI()?.clearAllFilters();
    statusMessage = "All filters cleared";
  }

  function handleGetInfo() {
    const api = tableRef?.getAPI();
    if (!api) return;
    const allRows = api.getAllRows();
    const hdrs = api.getHeaders();
    const sortState = api.getSortState();
    const filterState = api.getFilterState();
    const totalValue = allRows.reduce((sum: number, r: Record<string, unknown>) => sum + (r.price as number) * (r.stock as number), 0);
    const sortInfo = sortState ? `${sortState.key.label} (${sortState.direction})` : "None";
    alert(
      `Table Info:\n• Rows: ${allRows.length}\n• Columns: ${hdrs.length}\n• Active filters: ${Object.keys(filterState).length}\n• Sort: ${sortInfo}\n• Total inventory value: $${totalValue.toFixed(2)}`,
    );
    statusMessage = "Table info displayed";
  }
</script>

<div>
  <div style="margin-bottom: 12px; padding: 8px 12px; background-color: #eff6ff; border: 1px solid #bfdbfe; border-radius: 6px; color: #1e40af; font-size: 14px;">
    {statusMessage}
  </div>
  <div style="display: flex; gap: 8px; margin-bottom: 12px; flex-wrap: wrap;">
    <button onclick={handleSortByName}>Sort by Name (A-Z)</button>
    <button onclick={handleSortByPrice}>Sort by Price (High to Low)</button>
    <button onclick={handleFilterAvailable}>Filter: Available</button>
    <button onclick={handleClearFilters}>Clear Filters</button>
    <button onclick={handleGetInfo}>Get Table Info</button>
  </div>
  <SimpleTable
    bind:this={tableRef}
    defaultHeaders={headers}
    rows={programmaticControlConfig.rows}
    {height}
    {theme}
  />
</div>
