// packages/examples/svelte/src/demos/column-editor-custom-renderer/ColumnEditorCustomRendererDemo.svelte
<script lang="ts">
  import { SimpleTable } from "@simple-table/svelte";
  import type { Theme } from "@simple-table/svelte";
  import {
    columnEditorCustomRendererConfig,
    COLUMN_EDITOR_TEXT,
    COLUMN_EDITOR_SEARCH_PLACEHOLDER,
  } from "./column-editor-custom-renderer.demo-data";
  import ColumnEditorCustomRow from "./ColumnEditorCustomRow.svelte";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();

  const editorConfig = {
    text: COLUMN_EDITOR_TEXT,
    searchEnabled: true,
    searchPlaceholder: COLUMN_EDITOR_SEARCH_PLACEHOLDER,
    rowRenderer: ColumnEditorCustomRow,
  };
</script>

<SimpleTable
  defaultHeaders={columnEditorCustomRendererConfig.headers}
  rows={columnEditorCustomRendererConfig.rows}
  editColumns={true}
  columnEditorConfig={editorConfig}
  {height}
  {theme}
/>

// packages/examples/vue/src/demos/column-editor-custom-renderer/ColumnEditorCustomRendererDemo.vue
<script setup lang="ts">
import { SimpleTable } from "@simple-table/vue";
import type { Theme } from "@simple-table/vue";
import {
  columnEditorCustomRendererConfig,
  COLUMN_EDITOR_TEXT,
  COLUMN_EDITOR_SEARCH_PLACEHOLDER,
} from "./column-editor-custom-renderer.demo-data";
import ColumnEditorCustomRow from "./ColumnEditorCustomRow.vue";
import "@simple-table/vue/styles.css";

const props = withDefaults(defineProps<{ height?: string | number; theme?: Theme }>(), {
  height: "400px",
});

const editorConfig = {
  text: COLUMN_EDITOR_TEXT,
  searchEnabled: true,
  searchPlaceholder: COLUMN_EDITOR_SEARCH_PLACEHOLDER,
  rowRenderer: ColumnEditorCustomRow,
};
</script>

<template>
  <SimpleTable
    :default-headers="columnEditorCustomRendererConfig.headers"
    :rows="columnEditorCustomRendererConfig.rows"
    :edit-columns="true"
    :column-editor-config="editorConfig"
    :height="props.height"
    :theme="props.theme"
  />
</template>
