// packages/examples/svelte/src/demos/music/MusicFollowersCell.svelte
<script lang="ts">
  import type { CellRendererProps } from "@simple-table/svelte";
  import { getMusicThemeColors } from "./music.demo-data";
  import type { MusicArtist } from "./music.demo-data";
  import MusicTag from "./MusicTag.svelte";

  let { row, theme }: CellRendererProps = $props();
  const d = $derived(row as unknown as MusicArtist);
  const c = $derived(getMusicThemeColors(theme));
  const tagText = $derived(
    `↑ +${d.followersGrowthFormatted} (${d.followersGrowthPercent.toFixed(2)}%)`,
  );
</script>

<div style="display:flex;flex-direction:column;gap:4px;align-items:flex-start;">
  <div style="font-size:14px;color:{c.gray};">{d.followersFormatted}</div>
  <MusicTag text={tagText} variant="green" c={c} />
</div>

// packages/examples/angular/src/demos/music/music-followers-cell.component.ts
import { Component, Input } from "@angular/core";
import type { Row, Theme } from "@simple-table/angular";
import { getMusicThemeColors } from "./music.demo-data";
import type { MusicArtist } from "./music.demo-data";
import { MusicTagComponent } from "./music-tag.component";

@Component({
  standalone: true,
  selector: "demo-music-followers",
  imports: [MusicTagComponent],
  template: `
    <div style="display:flex;flex-direction:column;gap:4px;align-items:flex-start;">
      <div style="font-size:14px;" [style.color]="c.gray">{{ d.followersFormatted }}</div>
      <demo-music-tag [text]="tagText" variant="green" [theme]="theme" />
    </div>
  `,
})
export class MusicFollowersCellComponent {
  @Input({ required: true }) row!: Row;
  @Input() theme?: Theme;

  get d(): MusicArtist {
    return this.row as unknown as MusicArtist;
  }

  get c(): Record<string, string> {
    return getMusicThemeColors(this.theme);
  }

  get tagText(): string {
    return `↑ +${this.d.followersGrowthFormatted} (${this.d.followersGrowthPercent.toFixed(2)}%)`;
  }
}
