// packages/examples/svelte/src/demos/music/MusicDemo.svelte
<script lang="ts">
  import { SimpleTable } from "@simple-table/svelte";
  import type { Theme, SvelteHeaderObject, CellRenderer } from "@simple-table/svelte";
  import { musicData, musicHeaders } from "./music.demo-data";
  import "@simple-table/svelte/styles.css";
  import "./music-theme.css";
  import MusicArtistCell from "./MusicArtistCell.svelte";
  import MusicArtistTypeCell from "./MusicArtistTypeCell.svelte";
  import MusicFollowersCell from "./MusicFollowersCell.svelte";
  import MusicPlaylistReachCell from "./MusicPlaylistReachCell.svelte";
  import MusicPlaylistCountCell from "./MusicPlaylistCountCell.svelte";
  import MusicMonthlyListenersCell from "./MusicMonthlyListenersCell.svelte";
  import MusicPopularityCell from "./MusicPopularityCell.svelte";
  import MusicConversionRateCell from "./MusicConversionRateCell.svelte";
  import MusicRatioCell from "./MusicRatioCell.svelte";
  import MusicGrowthMetricCell from "./MusicGrowthMetricCell.svelte";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();

  const renderers: Record<string, unknown> = {
    artistName: MusicArtistCell,
    artistType: MusicArtistTypeCell,
    followers: MusicFollowersCell,
    followers7DayGrowth: MusicGrowthMetricCell,
    followers28DayGrowth: MusicGrowthMetricCell,
    followers60DayGrowth: MusicGrowthMetricCell,
    popularity: MusicPopularityCell,
    playlistReach: MusicPlaylistReachCell,
    playlistReach7DayGrowth: MusicGrowthMetricCell,
    playlistReach28DayGrowth: MusicGrowthMetricCell,
    playlistReach60DayGrowth: MusicGrowthMetricCell,
    playlistCount: MusicPlaylistCountCell,
    playlistCount7DayGrowth: MusicGrowthMetricCell,
    playlistCount28DayGrowth: MusicGrowthMetricCell,
    playlistCount60DayGrowth: MusicGrowthMetricCell,
    monthlyListeners: MusicMonthlyListenersCell,
    monthlyListeners7DayGrowth: MusicGrowthMetricCell,
    monthlyListeners28DayGrowth: MusicGrowthMetricCell,
    monthlyListeners60DayGrowth: MusicGrowthMetricCell,
    conversionRate: MusicConversionRateCell,
    reachFollowersRatio: MusicRatioCell,
  };

  function applyMusicCellRenderers(hdrs: SvelteHeaderObject[]): SvelteHeaderObject[] {
    return hdrs.map((h) => {
      const acc = String(h.accessor);
      const next: SvelteHeaderObject = { ...h };
      if (acc === "rank") next.pinned = "left";
      if (acc === "artistName") next.pinned = "left";
      const R = renderers[acc];
      if (R) next.cellRenderer = R as CellRenderer;
      if (h.children) next.children = applyMusicCellRenderers(h.children as SvelteHeaderObject[]);
      return next;
    });
  }

  const headers = $derived(
    applyMusicCellRenderers(JSON.parse(JSON.stringify(musicHeaders)) as SvelteHeaderObject[]),
  );
</script>

<div class="music-theme-container" style="font-family: Inter">
  <SimpleTable
    defaultHeaders={headers}
    rows={[...musicData]}
    {height}
    {theme}
    selectableCells={true}
    columnReordering={true}
    columnResizing={true}
    customTheme={{ headerHeight: 30, rowHeight: 85 }}
  />
</div>

// packages/examples/angular/src/demos/music/music-demo.component.ts
import { Component, Input } from "@angular/core";
import { SimpleTableComponent, asRows } from "@simple-table/angular";
import type { AngularCellRenderer, AngularHeaderObject, Theme } from "@simple-table/angular";
import { musicData, musicHeaders } from "./music.demo-data";
import { MusicArtistCellComponent } from "./music-artist-cell.component";
import { MusicArtistTypeCellComponent } from "./music-artist-type-cell.component";
import { MusicConversionRateCellComponent } from "./music-conversion-rate-cell.component";
import { MusicFollowersCellComponent } from "./music-followers-cell.component";
import { MusicGrowthMetricCellComponent } from "./music-growth-metric-cell.component";
import { MusicMonthlyListenersCellComponent } from "./music-monthly-listeners-cell.component";
import { MusicPlaylistCountCellComponent } from "./music-playlist-count-cell.component";
import { MusicPlaylistReachCellComponent } from "./music-playlist-reach-cell.component";
import { MusicPopularityCellComponent } from "./music-popularity-cell.component";
import { MusicRatioCellComponent } from "./music-ratio-cell.component";
import "@simple-table/angular/styles.css";
import "./music-theme.css";

const RENDERERS: Partial<Record<string, AngularCellRenderer>> = {
  artistName: MusicArtistCellComponent,
  artistType: MusicArtistTypeCellComponent,
  followers: MusicFollowersCellComponent,
  followers7DayGrowth: MusicGrowthMetricCellComponent,
  followers28DayGrowth: MusicGrowthMetricCellComponent,
  followers60DayGrowth: MusicGrowthMetricCellComponent,
  popularity: MusicPopularityCellComponent,
  playlistReach: MusicPlaylistReachCellComponent,
  playlistReach7DayGrowth: MusicGrowthMetricCellComponent,
  playlistReach28DayGrowth: MusicGrowthMetricCellComponent,
  playlistReach60DayGrowth: MusicGrowthMetricCellComponent,
  playlistCount: MusicPlaylistCountCellComponent,
  playlistCount7DayGrowth: MusicGrowthMetricCellComponent,
  playlistCount28DayGrowth: MusicGrowthMetricCellComponent,
  playlistCount60DayGrowth: MusicGrowthMetricCellComponent,
  monthlyListeners: MusicMonthlyListenersCellComponent,
  monthlyListeners7DayGrowth: MusicGrowthMetricCellComponent,
  monthlyListeners28DayGrowth: MusicGrowthMetricCellComponent,
  monthlyListeners60DayGrowth: MusicGrowthMetricCellComponent,
  conversionRate: MusicConversionRateCellComponent,
  reachFollowersRatio: MusicRatioCellComponent,
};

function applyMusicCellRenderers(hdrs: AngularHeaderObject[]): AngularHeaderObject[] {
  return hdrs.map((h): AngularHeaderObject => {
    const acc = String(h.accessor);
    const next: AngularHeaderObject = { ...h };
    const cellRenderer = RENDERERS[acc];
    if (cellRenderer) next.cellRenderer = cellRenderer;
    if (h.children) next.children = applyMusicCellRenderers(h.children);
    return next;
  });
}

@Component({
  selector: "music-demo",
  standalone: true,
  imports: [SimpleTableComponent],
  template: `
    <div class="music-theme-container" style="font-family: Inter">
      <simple-table
        [defaultHeaders]="headers"
        [rows]="rows"
        [height]="height"
        [theme]="theme"
        [selectableCells]="true"
        [columnReordering]="true"
        [columnResizing]="true"
        [customTheme]="{ headerHeight: 30, rowHeight: 85 }"
      ></simple-table>
    </div>
  `,
})
export class MusicDemoComponent {
  @Input() height: string | number = "400px";
  @Input() theme?: Theme;

  readonly rows = asRows([...musicData]);
  readonly headers: AngularHeaderObject[] = applyMusicCellRenderers(
    structuredClone(musicHeaders) as AngularHeaderObject[],
  );
}
