// packages/examples/svelte/src/demos/hr/HrPerformanceCell.svelte
<script lang="ts">
  import type { CellRendererProps } from "@simple-table/svelte";
  import { getHRThemeColors } from "./hr.demo-data";
  import type { HREmployee } from "./hr.demo-data";

  let { row, theme }: CellRendererProps = $props();
  const d = $derived(row as unknown as HREmployee);
  const score = $derived(d.performanceScore);
  const c = $derived(getHRThemeColors(theme));
  const barColor = $derived(score >= 90 ? c.progressSuccess : score >= 65 ? c.progressNormal : c.progressException);
</script>

<div style="width:100%;display:flex;flex-direction:column;">
  <div
    style="background-color:{c.progressBg};height:6px;width:100%;border-radius:100px;overflow:hidden;"
  >
    <div style="height:100%;width:{score}%;background-color:{barColor};border-radius:100px;"></div>
  </div>
  <div style="font-size:12px;text-align:center;margin-top:4px;color:{c.gray};">{score}/100</div>
</div>

// packages/examples/angular/src/demos/hr/hr-performance-cell.component.ts
import { Component, Input } from "@angular/core";
import type { Row, Theme } from "@simple-table/angular";
import { getHRThemeColors } from "./hr.demo-data";
import type { HREmployee } from "./hr.demo-data";

@Component({
  standalone: true,
  selector: "demo-hr-performance",
  template: `
    <div style="width:100%;display:flex;flex-direction:column;">
      <div
        style="height:6px;width:100%;border-radius:100px;overflow:hidden;"
        [style.background-color]="c.progressBg"
      >
        <div
          style="height:100%;border-radius:100px;"
          [style.width.%]="score"
          [style.background-color]="barColor"
        ></div>
      </div>
      <div style="font-size:12px;text-align:center;margin-top:4px;" [style.color]="c.gray">{{ score }}/100</div>
    </div>
  `,
})
export class HrPerformanceCellComponent {
  @Input({ required: true }) row!: Row;
  @Input() theme?: Theme;

  get d(): HREmployee {
    return this.row as unknown as HREmployee;
  }

  get score(): number {
    return this.d.performanceScore;
  }

  get c(): ReturnType<typeof getHRThemeColors> {
    return getHRThemeColors(this.theme);
  }

  get barColor(): string {
    const s = this.score;
    const colors = this.c;
    if (s >= 90) return colors.progressSuccess;
    if (s >= 65) return colors.progressNormal;
    return colors.progressException;
  }
}
