// packages/examples/angular/src/demos/aggregate-functions/aggregate-functions-demo.component.ts
import { Component, Input } from "@angular/core";
import {SimpleTableComponent} from "@simple-table/angular";import type { AngularHeaderObject, Row, Theme } from "@simple-table/angular";
import { aggregateFunctionsConfig } from "./aggregate-functions.demo-data";
import "@simple-table/angular/styles.css";

@Component({
  selector: "aggregate-functions-demo",
  standalone: true,
  imports: [SimpleTableComponent],
  template: `
    <simple-table
      [rows]="rows"
      [defaultHeaders]="headers"
      [rowGrouping]="grouping"
      [columnResizing]="true"
      [height]="height"
      [theme]="theme"
    ></simple-table>
  `,
})
export class AggregateFunctionsDemoComponent {
  @Input() height: string | number = "400px";
  @Input() theme?: Theme;

  readonly rows: Row[] = aggregateFunctionsConfig.rows;
  readonly headers: AngularHeaderObject[] = aggregateFunctionsConfig.headers;
  readonly grouping = aggregateFunctionsConfig.tableProps.rowGrouping;
}

// packages/examples/react/src/demos/aggregate-functions/AggregateFunctionsDemo.tsx
import {SimpleTable} from "@simple-table/react";import type { Theme } from "@simple-table/react";
import { aggregateFunctionsConfig } from "./aggregate-functions.demo-data";
import "@simple-table/react/styles.css";

const AggregateFunctionsDemo = ({
  height = "400px",
  theme,
}: {
  height?: string | number;
  theme?: Theme;
}) => {
  return (
    <SimpleTable
      defaultHeaders={aggregateFunctionsConfig.headers}
      rows={aggregateFunctionsConfig.rows}
      rowGrouping={aggregateFunctionsConfig.tableProps.rowGrouping}
      columnResizing
      height={height}
      theme={theme}
    />
  );
};

export default AggregateFunctionsDemo;
