// packages/examples/vue/src/demos/aggregate-functions/AggregateFunctionsDemo.vue
<template>
  <SimpleTable
    :default-headers="aggregateFunctionsConfig.headers"
    :rows="aggregateFunctionsConfig.rows"
    :row-grouping="aggregateFunctionsConfig.tableProps.rowGrouping"
    :column-resizing="true"
    :height="height"
    :theme="theme"
  />
</template>

<script setup lang="ts">
import {SimpleTable} from "@simple-table/vue";import type { Theme } from "@simple-table/vue";
import { aggregateFunctionsConfig } from "./aggregate-functions.demo-data";
import "@simple-table/vue/styles.css";

withDefaults(defineProps<{ height?: string | number; theme?: Theme }>(), {
  height: "400px",
});
</script>

// packages/examples/react/src/demos/aggregate-functions/AggregateFunctionsDemo.tsx
import {SimpleTable} from "@simple-table/react";import type { Theme } from "@simple-table/react";
import { aggregateFunctionsConfig } from "./aggregate-functions.demo-data";
import "@simple-table/react/styles.css";

const AggregateFunctionsDemo = ({
  height = "400px",
  theme,
}: {
  height?: string | number;
  theme?: Theme;
}) => {
  return (
    <SimpleTable
      defaultHeaders={aggregateFunctionsConfig.headers}
      rows={aggregateFunctionsConfig.rows}
      rowGrouping={aggregateFunctionsConfig.tableProps.rowGrouping}
      columnResizing
      height={height}
      theme={theme}
    />
  );
};

export default AggregateFunctionsDemo;
