// packages/examples/svelte/src/demos/external-sort/ExternalSortDemo.svelte
<script lang="ts">
  import {SimpleTable} from "@simple-table/svelte";  import type { Theme, SortColumn } from "@simple-table/svelte";
  import { externalSortConfig } from "./external-sort.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();

  let sortConfig = $state<SortColumn | null>(null);

  let sortedRows = $derived.by(() => {
    const data = [...externalSortConfig.rows];
    if (!sortConfig) return data;

    const accessor = sortConfig.key.accessor as string;
    const dir = sortConfig.direction === "asc" ? 1 : -1;

    return data.sort((a, b) => {
      const aVal = a[accessor];
      const bVal = b[accessor];
      if (aVal == null && bVal == null) return 0;
      if (aVal == null) return dir;
      if (bVal == null) return -dir;
      if (typeof aVal === "string" && typeof bVal === "string") return dir * aVal.localeCompare(bVal);
      return dir * (Number(aVal) - Number(bVal));
    });
  });

  function handleSortChange(sort: SortColumn | null) {
    sortConfig = sort;
  }
</script>

<SimpleTable
  defaultHeaders={externalSortConfig.headers}
  rows={sortedRows}
  externalSortHandling={true}
  columnResizing={externalSortConfig.tableProps.columnResizing}
  onSortChange={handleSortChange}
  {height}
  {theme}
/>

// packages/examples/angular/src/demos/external-sort/external-sort-demo.component.ts
import { Component, Input } from "@angular/core";
import {SimpleTableComponent, asRows} from "@simple-table/angular";import type { AngularHeaderObject, Row, SortColumn, Theme } from "@simple-table/angular";
import { externalSortConfig } from "./external-sort.demo-data";
import "@simple-table/angular/styles.css";

@Component({
  selector: "external-sort-demo",
  standalone: true,
  imports: [SimpleTableComponent],
  template: `
    <simple-table
      [rows]="sortedRows"
      [defaultHeaders]="headers"
      [height]="height"
      [theme]="theme"
      [externalSortHandling]="true"
      [columnResizing]="true"
      [onSortChange]="handleSortChange"
    ></simple-table>
  `,
})
export class ExternalSortDemoComponent {
  @Input() height: string | number = "400px";
  @Input() theme?: Theme;

  readonly headers: AngularHeaderObject[] = externalSortConfig.headers;
  private sortState: SortColumn | null = null;

  handleSortChange = (sort: SortColumn | null): void => {
    this.sortState = sort;
  };

  get sortedRows(): Row[] {
    const rows = [...asRows(externalSortConfig.rows)];
    if (!this.sortState) return rows;
    const accessor = this.sortState.key.accessor as string;
    const type = this.sortState.key.type;
    const dir = this.sortState.direction;
    return rows.sort((a, b) => {
      const aVal = a[accessor];
      const bVal = b[accessor];
      if (aVal === bVal) return 0;
      const cmp = type === "number"
        ? (aVal as number) - (bVal as number)
        : String(aVal).localeCompare(String(bVal));
      return dir === "asc" ? cmp : -cmp;
    });
  }
}
