// packages/examples/svelte/src/demos/column-width/ColumnWidthDemo.svelte
<script lang="ts">
  import {SimpleTable} from "@simple-table/svelte";  import type { Theme } from "@simple-table/svelte";
  import { columnWidthConfig } from "./column-width.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
  let isMobile = $state(false);

  function checkMobile() {
    isMobile = window.innerWidth < 768;
  }

  $effect(() => {
    checkMobile();
    window.addEventListener("resize", checkMobile);
    return () => window.removeEventListener("resize", checkMobile);
  });
</script>

<SimpleTable
  autoExpandColumns={!isMobile}
  columnResizing={true}
  defaultHeaders={columnWidthConfig.headers}
  rows={columnWidthConfig.rows}
  {height}
  {theme}
/>

// packages/examples/vue/src/demos/column-width/ColumnWidthDemo.vue
<template>
  <SimpleTable
    :auto-expand-columns="!isMobile"
    :column-resizing="true"
    :default-headers="columnWidthConfig.headers"
    :height="height"
    :rows="columnWidthConfig.rows"
    :theme="theme"
  />
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from "vue";
import {SimpleTable} from "@simple-table/vue";import type { Theme } from "@simple-table/vue";
import { columnWidthConfig } from "./column-width.demo-data";
import "@simple-table/vue/styles.css";

withDefaults(defineProps<{ height?: string | number; theme?: Theme }>(), {
  height: "400px",
});

const isMobile = ref(false);

function checkMobile() {
  isMobile.value = window.innerWidth < 768;
}

onMounted(() => {
  checkMobile();
  window.addEventListener("resize", checkMobile);
});

onUnmounted(() => {
  window.removeEventListener("resize", checkMobile);
});
</script>
