// packages/svelte/src/SimpleTable.svelte
<script lang="ts">
  import { onMount, onDestroy } from "svelte";
  import { SimpleTableVanilla } from "simple-table-core";
  import type { TableAPI } from "simple-table-core";
  import { buildVanillaConfig } from "./buildVanillaConfig";
  import type { SimpleTableSvelteProps, TableInstance } from "./types";

  // SimpleTable — Svelte adapter for simple-table-core.
  // Accepts the same props as SimpleTableProps with Svelte component types for renderers.
  // Use bind:this={tableRef} to access the TableAPI: tableRef.getAPI()?.sort(...)

  type $$Props = SimpleTableSvelteProps;

  export let rows: $$Props["rows"];
  export let defaultHeaders: $$Props["defaultHeaders"];

  // All remaining optional props — spread via $$restProps
  let container: HTMLDivElement;
  let instance: TableInstance | null = null;

  onMount(() => {
    instance = new SimpleTableVanilla(
      container,
      buildVanillaConfig({ rows, defaultHeaders, ...$$restProps } as SimpleTableSvelteProps)
    ) as unknown as TableInstance;
    instance.mount();
  });

  onDestroy(() => {
    instance?.destroy();
    instance = null;
  });

  // Reactive update: re-run whenever any prop changes.
  $: if (instance) {
    instance.update(
      buildVanillaConfig({ rows, defaultHeaders, ...$$restProps } as SimpleTableSvelteProps)
    );
  }

  /** Expose the TableAPI for consumers using bind:this. */
  export function getAPI(): TableAPI | null {
    return instance?.getAPI() ?? null;
  }
</script>

<div bind:this={container}></div>

// packages/solid/src/SimpleTable.tsx
import { createEffect, onCleanup, onMount } from "solid-js";
import { SimpleTableVanilla } from "simple-table-core";
import type { TableAPI } from "simple-table-core";
import { buildVanillaConfig } from "./buildVanillaConfig";
import type { SimpleTableSolidProps, TableInstance } from "./types";

/**
 * SimpleTable — Solid.js adapter for simple-table-core.
 *
 * Accepts the same props as SimpleTableProps (the vanilla user-facing API) but
 * with Solid component types for all renderer props.
 *
 * Pass a callback `ref` prop to receive the full TableAPI imperative interface:
 *
 * @example
 * let tableApi: TableAPI | undefined;
 *
 * <SimpleTable
 *   ref={(api) => (tableApi = api)}
 *   rows={rows()}
 *   defaultHeaders={headers}
 * />
 */
export function SimpleTable(props: SimpleTableSolidProps) {
  let containerEl!: HTMLDivElement;
  let instance: TableInstance | null = null;

  onMount(() => {
    instance = new SimpleTableVanilla(
      containerEl,
      buildVanillaConfig(props)
    ) as unknown as TableInstance;
    instance.mount();

    if (props.ref) {
      props.ref(instance.getAPI() as TableAPI);
    }
  });

  // Sync prop changes reactively. Solid tracks signal reads inside createEffect
  // so this re-runs whenever any reactive prop changes.
  createEffect(() => {
    if (instance) {
      instance.update(buildVanillaConfig(props));
    }
  });

  onCleanup(() => {
    instance?.destroy();
    instance = null;
  });

  return <div ref={containerEl} />;
}
