// packages/react/src/types.ts
import type React from "react";
import type {
  SimpleTableProps,
  SimpleTableConfig,
  HeaderObject,
  TableAPI,
  Row,
  CellRendererProps,
  HeaderRendererProps as VanillaHeaderRendererProps,
  FooterRendererProps as VanillaFooterRendererProps,
  LoadingStateRendererProps,
  ErrorStateRendererProps,
  EmptyStateRendererProps,
  HeaderDropdownProps as VanillaHeaderDropdownProps,
  ColumnEditorRowRendererProps as VanillaColumnEditorRowRendererProps,
  ColumnEditorCustomRendererProps,
  ColumnEditorConfig,
} from "simple-table-core";

// ─── Renderer prop overrides (React slots are nodes, not DOM IconElement) ─────
/** Passed to React `headerRenderer` / `headerDropdown`; slots are React nodes. */
export interface HeaderRendererComponents {
  sortIcon?: React.ReactNode;
  filterIcon?: React.ReactNode;
  collapseIcon?: React.ReactNode;
  labelContent?: React.ReactNode;
}

export type HeaderRendererProps = Omit<VanillaHeaderRendererProps, "components"> & {
  components?: HeaderRendererComponents;
};

/** Column editor row slots as React nodes (core uses `IconElement` / `HTMLElement`). */
export interface ColumnEditorRowRendererComponents {
  expandIcon?: React.ReactNode;
  checkbox?: React.ReactNode;
  dragIcon?: React.ReactNode;
  labelContent?: React.ReactNode;
  pinIcon?: React.ReactNode;
}

export type ColumnEditorRowRendererProps = Omit<
  VanillaColumnEditorRowRendererProps,
  "components"
> & {
  components: ColumnEditorRowRendererComponents;
};

export type FooterRendererProps = Omit<
  VanillaFooterRendererProps,
  "nextIcon" | "prevIcon"
> & {
  nextIcon?: React.ReactNode;
  prevIcon?: React.ReactNode;
};

export type HeaderDropdownProps = Omit<VanillaHeaderDropdownProps, "components"> & {
  components?: HeaderRendererComponents;
};

// ─── Internal instance contract ───────────────────────────────────────────────
// Used to type the internal ref inside SimpleTable without coupling to the
// concrete SimpleTableVanilla class.
export interface TableInstance {
  mount(): void;
  update(config: Partial<SimpleTableConfig>): void;
  destroy(): void;
  getAPI(): TableAPI;
}

// ─── Icon overrides ──────────────────────────────────────────────────────────
// Accept ReactNode in place of SVGSVGElement | HTMLElement | string
export type ReactIconElement = React.ReactNode;

export interface ReactIconsConfig {
  drag?: ReactIconElement;
  expand?: ReactIconElement;
  filter?: ReactIconElement;
  headerCollapse?: ReactIconElement;
  headerExpand?: ReactIconElement;
  next?: ReactIconElement;
  prev?: ReactIconElement;
  sortDown?: ReactIconElement;
  sortUp?: ReactIconElement;
  pinnedLeftIcon?: ReactIconElement;
  pinnedRightIcon?: ReactIconElement;
}

// ─── Renderer overrides ───────────────────────────────────────────────────────
// Allow class/function components or inline render props that return ReactNode (string, number, etc.).
export type ReactCellRenderer =
  | React.ComponentType<CellRendererProps>
  | ((props: CellRendererProps) => React.ReactNode);
export type ReactHeaderRenderer =
  | React.ComponentType<HeaderRendererProps>
  | ((props: HeaderRendererProps) => React.ReactNode);
export type ReactFooterRenderer =
  | React.ComponentType<FooterRendererProps>
  | ((props: FooterRendererProps) => React.ReactNode);
export type ReactHeaderDropdown =
  | React.ComponentType<HeaderDropdownProps>
  | ((props: HeaderDropdownProps) => React.ReactNode);
export type ReactColumnEditorRowRenderer =
  | React.ComponentType<ColumnEditorRowRendererProps>
  | ((props: ColumnEditorRowRendererProps) => React.ReactNode);
export type ReactColumnEditorCustomRenderer =
  | React.ComponentType<ColumnEditorCustomRendererProps>
  | ((props: ColumnEditorCustomRendererProps) => React.ReactNode);

// State renderers can be a component (receives props) or a plain ReactNode (static markup)
export type ReactLoadingStateRenderer =
  | React.ComponentType<LoadingStateRendererProps>
  | React.ReactNode;
export type ReactErrorStateRenderer =
  | React.ComponentType<ErrorStateRendererProps>
  | React.ReactNode;
export type ReactEmptyStateRenderer =
  | React.ComponentType<EmptyStateRendererProps>
  | React.ReactNode;

// ─── Column editor config override ───────────────────────────────────────────
export interface ReactColumnEditorConfig extends Omit<
  ColumnEditorConfig,
  "rowRenderer" | "customRenderer"
> {
  rowRenderer?: ReactColumnEditorRowRenderer;
  customRenderer?: ReactColumnEditorCustomRenderer;
}

// ─── HeaderObject override ────────────────────────────────────────────────────
/**
 * Column definition for `defaultHeaders`: same column metadata as core columns, but
 * `cellRenderer` / `headerRenderer` / `children` / `nestedTable` are React-only.
 */
export interface ReactHeaderObject extends Omit<
  HeaderObject,
  "cellRenderer" | "headerRenderer" | "children" | "nestedTable"
> {
  cellRenderer?: ReactCellRenderer;
  headerRenderer?: ReactHeaderRenderer;
  children?: ReadonlyArray<ReactHeaderObject>;
  /** Nested grid: React table props minus row data and inherited state renderers. */
  nestedTable?: Omit<
    SimpleTableReactProps,
    | "rows"
    | "loadingStateRenderer"
    | "errorStateRenderer"
    | "emptyStateRenderer"
    | "tableEmptyStateRenderer"
  >;
}

// ─── Top-level props ──────────────────────────────────────────────────────────
// Mirrors SimpleTableProps with React-specific renderer/icon types. Use `ref` +
// `forwardRef<TableAPI, …>` for the imperative API.
//
//   Overridden to React equivalents:
//     - defaultHeaders         → ReadonlyArray<ReactHeaderObject>
//     - footerRenderer         → React.ComponentType<FooterRendererProps>
//     - loadingStateRenderer   → React.ComponentType<…> | React.ReactNode
//     - errorStateRenderer     → React.ComponentType<…> | React.ReactNode
//     - emptyStateRenderer     → React.ComponentType<…> | React.ReactNode
//     - tableEmptyStateRenderer → React.ReactNode
//     - headerDropdown         → React.ComponentType<HeaderDropdownProps>
//     - columnEditorConfig     → ReactColumnEditorConfig
//     - icons                  → ReactIconsConfig
export interface SimpleTableReactProps extends Omit<
  SimpleTableProps,
  // Overridden below with React types
  | "defaultHeaders"
  | "footerRenderer"
  | "emptyStateRenderer"
  | "errorStateRenderer"
  | "loadingStateRenderer"
  | "tableEmptyStateRenderer"
  | "headerDropdown"
  | "columnEditorConfig"
  | "icons"
  | "rows"
  | "onColumnOrderChange"
  | "onColumnWidthChange"
  | "onHeaderEdit"
  | "onColumnSelect"
> {
  defaultHeaders: ReadonlyArray<ReactHeaderObject>;
  onColumnOrderChange?: (newHeaders: ReactHeaderObject[]) => void;
  onColumnWidthChange?: (headers: ReactHeaderObject[]) => void;
  onHeaderEdit?: (header: ReactHeaderObject, newLabel: string) => void;
  onColumnSelect?: (header: ReactHeaderObject) => void;
  /** Row data: any object rows (domain models) or core `Row[]`; cast to vanilla `Row[]` inside the adapter. */
  rows: ReadonlyArray<Row> | ReadonlyArray<object>;
  footerRenderer?: ReactFooterRenderer;
  loadingStateRenderer?: ReactLoadingStateRenderer;
  errorStateRenderer?: ReactErrorStateRenderer;
  emptyStateRenderer?: ReactEmptyStateRenderer;
  tableEmptyStateRenderer?: React.ReactNode;
  headerDropdown?: ReactHeaderDropdown;
  columnEditorConfig?: ReactColumnEditorConfig;
  icons?: ReactIconsConfig;
}

// Re-export vanilla prop types that consumers still need directly
export type {
  CellRendererProps,
  LoadingStateRendererProps,
  ErrorStateRendererProps,
  EmptyStateRendererProps,
  ColumnEditorCustomRendererProps,
};

// packages/solid/src/types.ts
import type { Component, JSX } from "solid-js";
import type {
  SimpleTableProps,
  SimpleTableConfig,
  HeaderObject,
  Row,
  TableAPI,
  CellRendererProps,
  HeaderRendererProps,
  FooterRendererProps,
  LoadingStateRendererProps,
  ErrorStateRendererProps,
  EmptyStateRendererProps,
  HeaderDropdownProps,
  ColumnEditorRowRendererProps,
  ColumnEditorCustomRendererProps,
  ColumnEditorConfig,
} from "simple-table-core";

// ─── Internal instance contract ───────────────────────────────────────────────
export interface TableInstance {
  mount(): void;
  update(config: Partial<SimpleTableConfig>): void;
  destroy(): void;
  getAPI(): TableAPI;
}

// ─── Icon overrides ───────────────────────────────────────────────────────────
// Accept Solid JSX.Element in place of SVGSVGElement | HTMLElement | string
export type SolidIconElement = JSX.Element;

export interface SolidIconsConfig {
  drag?: SolidIconElement;
  expand?: SolidIconElement;
  filter?: SolidIconElement;
  headerCollapse?: SolidIconElement;
  headerExpand?: SolidIconElement;
  next?: SolidIconElement;
  prev?: SolidIconElement;
  sortDown?: SolidIconElement;
  sortUp?: SolidIconElement;
  pinnedLeftIcon?: SolidIconElement;
  pinnedRightIcon?: SolidIconElement;
}

// ─── Renderer overrides ───────────────────────────────────────────────────────
export type SolidCellRenderer = Component<CellRendererProps>;
export type SolidHeaderRenderer = Component<HeaderRendererProps>;
export type SolidFooterRenderer = Component<FooterRendererProps>;
export type SolidHeaderDropdown = Component<HeaderDropdownProps>;
export type SolidColumnEditorRowRenderer = Component<ColumnEditorRowRendererProps>;
export type SolidColumnEditorCustomRenderer = Component<ColumnEditorCustomRendererProps>;

// State renderers can be a component (receives props) or a plain JSX.Element (static markup)
export type SolidLoadingStateRenderer = Component<LoadingStateRendererProps> | JSX.Element;
export type SolidErrorStateRenderer = Component<ErrorStateRendererProps> | JSX.Element;
export type SolidEmptyStateRenderer = Component<EmptyStateRendererProps> | JSX.Element;

// ─── Column editor config override ───────────────────────────────────────────
export interface SolidColumnEditorConfig
  extends Omit<ColumnEditorConfig, "rowRenderer" | "customRenderer"> {
  rowRenderer?: SolidColumnEditorRowRenderer;
  customRenderer?: SolidColumnEditorCustomRenderer;
}

// ─── HeaderObject override ────────────────────────────────────────────────────
/**
 * Column definition for `defaultHeaders`: core column metadata with Solid-only
 * renderer fields. `defaultHeaders` also accepts plain `HeaderObject[]` from shared configs.
 */
export interface SolidHeaderObject
  extends Omit<HeaderObject, "cellRenderer" | "headerRenderer" | "children" | "nestedTable"> {
  cellRenderer?: SolidCellRenderer;
  headerRenderer?: SolidHeaderRenderer;
  children?: SolidHeaderObject[];
  nestedTable?: Omit<
    SimpleTableSolidProps,
    | "rows"
    | "loadingStateRenderer"
    | "errorStateRenderer"
    | "emptyStateRenderer"
    | "tableEmptyStateRenderer"
  >;
}

// ─── Top-level props ──────────────────────────────────────────────────────────
// Mirrors SimpleTableProps with Solid-specific overrides. Pass `ref` to receive
// the TableAPI once mounted (callback ref).
export interface SimpleTableSolidProps
  extends Omit<
    SimpleTableProps,
    | "rows"
    | "defaultHeaders"
    | "footerRenderer"
    | "emptyStateRenderer"
    | "errorStateRenderer"
    | "loadingStateRenderer"
    | "tableEmptyStateRenderer"
    | "headerDropdown"
    | "columnEditorConfig"
    | "icons"
    | "onColumnOrderChange"
    | "onColumnWidthChange"
    | "onHeaderEdit"
    | "onColumnSelect"
  > {
  defaultHeaders: ReadonlyArray<HeaderObject | SolidHeaderObject>;
  /** Row data: domain objects or core `Row[]`; cast inside the adapter. */
  rows: ReadonlyArray<Row> | ReadonlyArray<object>;
  onColumnOrderChange?: (newHeaders: SolidHeaderObject[]) => void;
  onColumnWidthChange?: (headers: SolidHeaderObject[]) => void;
  onHeaderEdit?: (header: SolidHeaderObject, newLabel: string) => void;
  onColumnSelect?: (header: SolidHeaderObject) => void;
  footerRenderer?: SolidFooterRenderer;
  loadingStateRenderer?: SolidLoadingStateRenderer;
  errorStateRenderer?: SolidErrorStateRenderer;
  emptyStateRenderer?: SolidEmptyStateRenderer;
  tableEmptyStateRenderer?: JSX.Element;
  headerDropdown?: SolidHeaderDropdown;
  columnEditorConfig?: SolidColumnEditorConfig;
  icons?: SolidIconsConfig;
  /** Callback ref — receives the TableAPI once the table is mounted. */
  ref?: (api: TableAPI) => void;
}

// Re-export vanilla prop types that consumers still need directly
export type {
  CellRendererProps,
  HeaderRendererProps,
  FooterRendererProps,
  LoadingStateRendererProps,
  ErrorStateRendererProps,
  EmptyStateRendererProps,
  HeaderDropdownProps,
  ColumnEditorRowRendererProps,
  ColumnEditorCustomRendererProps,
};
