// packages/examples/svelte/src/demos/collapsible-columns/CollapsibleColumnsDemo.svelte
<script lang="ts">
  import {SimpleTable} from "@simple-table/svelte";  import type { Theme } from "@simple-table/svelte";
  import { collapsibleColumnsConfig } from "./collapsible-columns.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
</script>

<SimpleTable
  defaultHeaders={collapsibleColumnsConfig.headers}
  rows={collapsibleColumnsConfig.rows}
  columnResizing={true}
  editColumns={true}
  selectableCells={true}
  columnReordering={true}
  {height}
  {theme}
/>

// packages/examples/angular/src/demos/collapsible-columns/collapsible-columns-demo.component.ts
import { Component, Input } from "@angular/core";
import {SimpleTableComponent} from "@simple-table/angular";import type { AngularHeaderObject, Row, Theme } from "@simple-table/angular";
import { collapsibleColumnsConfig } from "./collapsible-columns.demo-data";
import "@simple-table/angular/styles.css";

@Component({
  selector: "collapsible-columns-demo",
  standalone: true,
  imports: [SimpleTableComponent],
  template: `
    <simple-table
      [rows]="rows"
      [defaultHeaders]="headers"
      [columnResizing]="true"
      [editColumns]="true"
      [selectableCells]="true"
      [columnReordering]="true"
      [height]="height"
      [theme]="theme"
    ></simple-table>
  `,
})
export class CollapsibleColumnsDemoComponent {
  @Input() height: string | number = "400px";
  @Input() theme?: Theme;

  readonly rows: Row[] = collapsibleColumnsConfig.rows;
  readonly headers: AngularHeaderObject[] = collapsibleColumnsConfig.headers;
}
