// packages/examples/svelte/src/demos/column-filtering/ColumnFilteringDemo.svelte
<script lang="ts">
  import {SimpleTable} from "@simple-table/svelte";  import type { Theme } from "@simple-table/svelte";
  import { columnFilteringConfig } from "./column-filtering.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
</script>

<SimpleTable
  defaultHeaders={columnFilteringConfig.headers}
  rows={columnFilteringConfig.rows}
  {height}
  {theme}
/>

// packages/examples/angular/src/demos/column-filtering/column-filtering-demo.component.ts
import { Component, Input } from "@angular/core";
import {SimpleTableComponent} from "@simple-table/angular";import type { AngularHeaderObject, Row, Theme } from "@simple-table/angular";
import { columnFilteringConfig } from "./column-filtering.demo-data";
import "@simple-table/angular/styles.css";

@Component({
  selector: "column-filtering-demo",
  standalone: true,
  imports: [SimpleTableComponent],
  template: `
    <simple-table
      [rows]="rows"
      [defaultHeaders]="headers"
      [height]="height"
      [theme]="theme"
    ></simple-table>
  `,
})
export class ColumnFilteringDemoComponent {
  @Input() height: string | number = "400px";
  @Input() theme?: Theme;

  readonly rows: Row[] = columnFilteringConfig.rows;
  readonly headers: AngularHeaderObject[] = columnFilteringConfig.headers;
}
