// packages/examples/vue/src/demos/pagination/PaginationDemo.vue
<template>
  <SimpleTable
    :default-headers="paginationConfig.headers"
    :height="height ?? 'auto'"
    :is-loading="isLoading"
    :on-next-page="onNextPage"
    :rows="rows"
    :rows-per-page="PAGINATION_ROWS_PER_PAGE"
    :should-paginate="true"
    :theme="theme"
  />
</template>

<script setup lang="ts">
import { ref } from "vue";
import {SimpleTable} from "@simple-table/vue";import type { Theme } from "@simple-table/vue";
import { paginationConfig, paginationData, PAGINATION_ROWS_PER_PAGE } from "./pagination.demo-data";
import "@simple-table/vue/styles.css";

const props = withDefaults(defineProps<{ height?: string | number; theme?: Theme }>(), {});

const rows = ref(paginationData.slice(0, PAGINATION_ROWS_PER_PAGE));
const isLoading = ref(false);

const onNextPage = async (pageIndex: number) => {
  const startIndex = pageIndex * PAGINATION_ROWS_PER_PAGE;
  const endIndex = startIndex + PAGINATION_ROWS_PER_PAGE;

  isLoading.value = true;
  await new Promise((resolve) => setTimeout(resolve, 800));
  const newPageData = paginationData.slice(startIndex, endIndex);

  if (newPageData.length === 0 || rows.value.length > startIndex) {
    isLoading.value = false;
    return false;
  }

  rows.value = [...rows.value, ...newPageData];
  isLoading.value = false;
  return true;
};
</script>

// packages/examples/svelte/src/demos/pagination/PaginationDemo.svelte
<script lang="ts">
  import {SimpleTable} from "@simple-table/svelte";  import type { Theme } from "@simple-table/svelte";
  import { paginationConfig, paginationData, PAGINATION_ROWS_PER_PAGE } from "./pagination.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height, theme }: { height?: string | number; theme?: Theme } = $props();

  let rows = $state(paginationData.slice(0, PAGINATION_ROWS_PER_PAGE));
  let isLoading = $state(false);

  const onNextPage = async (pageIndex: number) => {
    const startIndex = pageIndex * PAGINATION_ROWS_PER_PAGE;
    const endIndex = startIndex + PAGINATION_ROWS_PER_PAGE;

    isLoading = true;
    await new Promise((resolve) => setTimeout(resolve, 800));
    const newPageData = paginationData.slice(startIndex, endIndex);

    if (newPageData.length === 0 || rows.length > startIndex) {
      isLoading = false;
      return false;
    }

    rows = [...rows, ...newPageData];
    isLoading = false;
    return true;
  };
</script>

<SimpleTable
  defaultHeaders={paginationConfig.headers}
  height={height ?? "auto"}
  {isLoading}
  {onNextPage}
  {rows}
  rowsPerPage={PAGINATION_ROWS_PER_PAGE}
  shouldPaginate={true}
  {theme}
/>
