// packages/examples/angular/src/demos/empty-state/empty-state-demo.component.ts
import { ApplicationRef, Component, EnvironmentInjector, Input, inject } from "@angular/core";
import { SimpleTableComponent, wrapAngularRenderer } from "@simple-table/angular";
import type { AngularHeaderObject, Row, Theme } from "@simple-table/angular";
import { emptyStateConfig } from "./empty-state.demo-data";
import { TableEmptyStateComponent } from "./table-empty-state.component";
import "@simple-table/angular/styles.css";

@Component({
  selector: "empty-state-demo",
  standalone: true,
  imports: [SimpleTableComponent],
  template: `
    <simple-table
      [rows]="rows"
      [defaultHeaders]="headers"
      [height]="height"
      [theme]="theme"
      [tableEmptyStateRenderer]="emptyStateEl"
    ></simple-table>
  `,
})
export class EmptyStateDemoComponent {
  @Input() height: string | number = "400px";
  @Input() theme?: Theme;

  private readonly appRef = inject(ApplicationRef);
  private readonly envInjector = inject(EnvironmentInjector);

  readonly rows: Row[] = emptyStateConfig.rows;
  readonly headers: AngularHeaderObject[] = emptyStateConfig.headers;
  readonly emptyStateEl = wrapAngularRenderer(
    TableEmptyStateComponent,
    this.appRef,
    this.envInjector,
  )({});
}

// packages/examples/svelte/src/demos/empty-state/EmptyStateDemo.svelte
<script lang="ts">
  import { SimpleTable } from "@simple-table/svelte";
  import type { Theme } from "@simple-table/svelte";
  import { emptyStateConfig } from "./empty-state.demo-data";
  import TableEmptyState from "./TableEmptyState.svelte";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
</script>

<SimpleTable
  defaultHeaders={emptyStateConfig.headers}
  rows={emptyStateConfig.rows}
  tableEmptyStateRenderer={TableEmptyState}
  {height}
  {theme}
/>
