// packages/examples/svelte/src/demos/custom-theme/CustomThemeDemo.svelte
<script lang="ts">
  import {SimpleTable} from "@simple-table/svelte";  import type { Theme } from "@simple-table/svelte";
  import { customThemeConfig } from "./custom-theme.demo-data";
  import "@simple-table/svelte/styles.css";
  import "./custom-theme.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
</script>

<SimpleTable
  defaultHeaders={customThemeConfig.headers}
  rows={customThemeConfig.rows}
  theme={theme ?? "custom"}
  customTheme={customThemeConfig.tableProps.customTheme}
  columnResizing={true}
  selectableCells={true}
  {height}
/>

// packages/examples/solid/src/demos/custom-theme/CustomThemeDemo.tsx
import {SimpleTable} from "@simple-table/solid";import type { Theme } from "@simple-table/solid";
import { customThemeConfig } from "./custom-theme.demo-data";
import "@simple-table/solid/styles.css";
import "./custom-theme.css";

export default function CustomThemeDemo(props: { height?: string | number; theme?: Theme }) {
  return (
    <SimpleTable
      defaultHeaders={customThemeConfig.headers}
      rows={customThemeConfig.rows}
      height={props.height ?? "400px"}
      theme={props.theme ?? "custom"}
      customTheme={customThemeConfig.tableProps.customTheme}
      columnResizing
      selectableCells
    />
  );
}
