// packages/examples/solid/src/demos/loading-state/LoadingStateDemo.tsx
import { createSignal, onMount, onCleanup } from "solid-js";
import {SimpleTable} from "@simple-table/solid";import type { Theme, Row } from "@simple-table/solid";
import { loadingStateConfig } from "./loading-state.demo-data";
import "@simple-table/solid/styles.css";

export default function LoadingStateDemo(props: { height?: string | number; theme?: Theme }) {
  const [isLoading, setIsLoading] = createSignal(true);
  const [data, setData] = createSignal<Row[]>([]);
  let timer: ReturnType<typeof setTimeout> | null = null;

  const loadData = () => {
    setIsLoading(true);
    setData([]);
    if (timer) clearTimeout(timer);
    timer = setTimeout(() => {
      setData(loadingStateConfig.rows as Row[]);
      setIsLoading(false);
    }, 2000);
  };

  onMount(() => loadData());
  onCleanup(() => { if (timer) clearTimeout(timer); });

  return (
    <div>
      <div style={{ "margin-bottom": "12px" }}>
        <button
          onClick={loadData}
          disabled={isLoading()}
          style={{ padding: "6px 16px", cursor: isLoading() ? "not-allowed" : "pointer" }}
        >
          {isLoading() ? "Loading\u2026" : "Reload Data"}
        </button>
      </div>
      <SimpleTable
        defaultHeaders={loadingStateConfig.headers}
        rows={data()}
        isLoading={isLoading()}
        height={props.height ?? "400px"}
        theme={props.theme}
      />
    </div>
  );
}

// packages/examples/angular/src/demos/loading-state/loading-state-demo.component.ts
import { Component, Input, OnInit, OnDestroy } from "@angular/core";
import {SimpleTableComponent} from "@simple-table/angular";import type { AngularHeaderObject, Row, Theme } from "@simple-table/angular";
import { loadingStateConfig } from "./loading-state.demo-data";
import "@simple-table/angular/styles.css";

@Component({
  selector: "loading-state-demo",
  standalone: true,
  imports: [SimpleTableComponent],
  template: `
    <div>
      <div style="margin-bottom: 12px">
        <button
          (click)="loadData()"
          [disabled]="isLoading"
          [style.padding]="'6px 16px'"
          [style.cursor]="isLoading ? 'not-allowed' : 'pointer'"
        >
          {{ isLoading ? 'Loading\u2026' : 'Reload Data' }}
        </button>
      </div>
      <simple-table
        [rows]="data"
        [defaultHeaders]="headers"
        [height]="height"
        [theme]="theme"
        [isLoading]="isLoading"
      ></simple-table>
    </div>
  `,
})
export class LoadingStateDemoComponent implements OnInit, OnDestroy {
  @Input() height: string | number = "400px";
  @Input() theme?: Theme;

  readonly headers: AngularHeaderObject[] = loadingStateConfig.headers;
  data: Row[] = [];
  isLoading = true;
  private timer: ReturnType<typeof setTimeout> | null = null;

  ngOnInit(): void {
    this.loadData();
  }

  ngOnDestroy(): void {
    if (this.timer) clearTimeout(this.timer);
  }

  loadData(): void {
    this.isLoading = true;
    this.data = [];
    if (this.timer) clearTimeout(this.timer);
    this.timer = setTimeout(() => {
      this.data = loadingStateConfig.rows as Row[];
      this.isLoading = false;
    }, 2000);
  }
}
