// packages/examples/angular/src/demos/animations/animations-demo.component.ts
import { Component, Input } from "@angular/core";
import { SimpleTableComponent } from "@simple-table/angular";
import type { AngularHeaderObject, Row, Theme } from "@simple-table/angular";
import { animationsConfig } from "./animations.demo-data";
import "@simple-table/angular/styles.css";

@Component({
  selector: "animations-demo",
  standalone: true,
  imports: [SimpleTableComponent],
  template: `
    <simple-table
      [rows]="rows"
      [defaultHeaders]="headers"
      [height]="height"
      [theme]="theme"
      [columnReordering]="true"
      [editColumns]="true"
      [editColumnsInitOpen]="true"
      (columnOrderChange)="onColumnOrderChange($event)"
    ></simple-table>
  `,
})
export class AnimationsDemoComponent {
  @Input() height: string | number = "400px";
  @Input() theme?: Theme;

  readonly rows: Row[] = animationsConfig.rows;
  headers: AngularHeaderObject[] = [...animationsConfig.headers];

  onColumnOrderChange(newHeaders: AngularHeaderObject[]): void {
    this.headers = newHeaders;
  }
}

// packages/examples/svelte/src/demos/animations/AnimationsDemo.svelte
<script lang="ts">
  import { SimpleTable } from "@simple-table/svelte";
  import type { Theme, SvelteHeaderObject } from "@simple-table/svelte";
  import { animationsConfig } from "./animations.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
  let headers: SvelteHeaderObject[] = $state([...animationsConfig.headers]);

  function handleColumnOrderChange(newHeaders: SvelteHeaderObject[]) {
    headers = newHeaders;
  }
</script>

<SimpleTable
  columnReordering
  defaultHeaders={headers}
  editColumns
  editColumnsInitOpen
  rows={animationsConfig.rows}
  {height}
  {theme}
  onColumnOrderChange={handleColumnOrderChange}
/>
