// packages/examples/react/src/demos/sales/SalesDemo.tsx
import { useState, useEffect } from "react";
import { SimpleTable } from "@simple-table/react";
import type { Theme, CellChangeProps } from "@simple-table/react";
import { salesSampleRows, type SalesRow } from "./sales.demo-data";
import { SALES_HEADERS } from "./sales-headers";
import "@simple-table/react/styles.css";

function formatTableHeight(height?: string | number | null): string {
  if (height == null) return "70dvh";
  if (typeof height === "number") return `${height}px`;
  return height;
}

const SalesDemo = ({ height, theme }: { height?: string | number | null; theme?: Theme }) => {
  const [data, setData] = useState<SalesRow[]>(() => salesSampleRows.map((r) => ({ ...r })));
  const [isMobile, setIsMobile] = useState(false);

  useEffect(() => {
    const checkMobile = () => setIsMobile(window.innerWidth < 768);
    checkMobile();
    window.addEventListener("resize", checkMobile);
    return () => window.removeEventListener("resize", checkMobile);
  }, []);

  const handleCellEdit = ({ accessor, newValue, row }: CellChangeProps) => {
    setData((prev) =>
      prev.map((item) => (item.id === row.id ? { ...item, [accessor]: newValue } : item)),
    );
  };

  return (
    <SimpleTable
      autoExpandColumns={!isMobile}
      columnResizing
      columnReordering
      defaultHeaders={SALES_HEADERS}
      editColumns
      height={formatTableHeight(height)}
      initialSortColumn="dealValue"
      initialSortDirection="desc"
      onCellEdit={handleCellEdit}
      rows={data}
      selectableCells
      theme={theme}
    />
  );
};

export default SalesDemo;

// packages/examples/svelte/src/demos/sales/SalesDemo.svelte
<script lang="ts">
  import { onMount, onDestroy } from "svelte";
  import { SimpleTable } from "@simple-table/svelte";
  import type { Theme, SvelteHeaderObject, CellChangeProps, Row } from "@simple-table/svelte";
  import { salesHeadersCore, salesSampleRows } from "./sales.demo-data";
  import SalesDealValueCell from "./SalesDealValueCell.svelte";
  import SalesIsWonCell from "./SalesIsWonCell.svelte";
  import SalesCommissionCell from "./SalesCommissionCell.svelte";
  import SalesProfitMarginCell from "./SalesProfitMarginCell.svelte";
  import SalesDealProfitCell from "./SalesDealProfitCell.svelte";
  import "@simple-table/svelte/styles.css";

  let { height, theme }: { height?: string | number | null; theme?: Theme } = $props();

  function formatTableHeight(h?: string | number | null): string {
    if (h == null) return "70dvh";
    if (typeof h === "number") return `${h}px`;
    return h;
  }

  const renderers: Record<string, unknown> = {
    dealValue: SalesDealValueCell,
    isWon: SalesIsWonCell,
    commission: SalesCommissionCell,
    profitMargin: SalesProfitMarginCell,
    dealProfit: SalesDealProfitCell,
  };

  function applyCellComponents(hdrs: SvelteHeaderObject[]): SvelteHeaderObject[] {
    return hdrs.map((h) => ({
      ...h,
      ...(renderers[h.accessor as string] ? { cellRenderer: renderers[h.accessor as string] } : {}),
      ...(h.children ? { children: applyCellComponents(h.children as SvelteHeaderObject[]) } : {}),
    }));
  }

  const headers = $derived(
    applyCellComponents(JSON.parse(JSON.stringify(salesHeadersCore)) as SvelteHeaderObject[]),
  );

  let data = $state<Row[]>(salesSampleRows.map((r) => ({ ...r })) as Row[]);
  let isMobile = $state(false);

  function checkMobile() {
    isMobile = window.innerWidth < 768;
  }

  onMount(() => {
    checkMobile();
    window.addEventListener("resize", checkMobile);
  });

  onDestroy(() => {
    window.removeEventListener("resize", checkMobile);
  });

  function handleCellEdit({ accessor, newValue, row }: CellChangeProps) {
    data = data.map((item) => (item.id === row.id ? { ...item, [accessor]: newValue } : item)) as Row[];
  }
</script>

<SimpleTable
  defaultHeaders={headers}
  rows={data}
  height={formatTableHeight(height)}
  {theme}
  autoExpandColumns={!isMobile}
  editColumns={true}
  selectableCells={true}
  columnResizing={true}
  columnReordering={true}
  initialSortColumn="dealValue"
  initialSortDirection="desc"
  onCellEdit={handleCellEdit}
/>
