// packages/examples/angular/src/demos/infrastructure/infrastructure-demo.component.ts
import { AfterViewInit, Component, Input, OnDestroy, ViewChild } from "@angular/core";
import { SimpleTableComponent } from "@simple-table/angular";
import type { AngularHeaderObject, Row, Theme, ValueGetterProps } from "@simple-table/angular";
import { infrastructureData } from "./infrastructure.demo-data";
import {
  InfraCpuCellComponent,
  InfraDiskCellComponent,
  InfraMemoryCellComponent,
  InfraResponseCellComponent,
  InfraServerIdCellComponent,
  InfraStatusCellComponent,
} from "./infrastructure-cell-components";
import { startInfraDemoLiveUpdates } from "./infrastructure-live-updates";
import "@simple-table/angular/styles.css";

function getHeaders(theme?: Theme): AngularHeaderObject[] {
  return [
    {
      accessor: "serverId",
      align: "left",
      filterable: true,
      isEditable: false,
      isSortable: true,
      label: "Server ID",
      minWidth: 180,
      pinned: "left",
      type: "string",
      width: "1.2fr",
      cellRenderer: InfraServerIdCellComponent,
    },
    {
      accessor: "serverName",
      align: "left",
      filterable: true,
      isEditable: false,
      isSortable: true,
      label: "Name",
      minWidth: 200,
      type: "string",
      width: "1.5fr",
    },
    {
      accessor: "performance",
      label: "Performance Metrics",
      width: 690,
      isSortable: false,
      children: [
        {
          accessor: "cpuHistory",
          label: "CPU History",
          width: 150,
          isSortable: false,
          filterable: false,
          isEditable: false,
          align: "center",
          type: "lineAreaChart",
          tooltip: "CPU usage over the last 30 intervals",
        },
        {
          accessor: "cpuUsage",
          label: "CPU %",
          width: 120,
          isSortable: true,
          filterable: true,
          isEditable: true,
          align: "right",
          type: "number",
          cellRenderer: InfraCpuCellComponent,
        },
        {
          accessor: "memoryUsage",
          label: "Memory %",
          width: 130,
          isSortable: true,
          filterable: true,
          isEditable: true,
          align: "right",
          type: "number",
          cellRenderer: InfraMemoryCellComponent,
        },
        {
          accessor: "diskUsage",
          label: "Disk %",
          width: 120,
          isSortable: true,
          filterable: true,
          isEditable: true,
          align: "right",
          type: "number",
          cellRenderer: InfraDiskCellComponent,
        },
        {
          accessor: "responseTime",
          label: "Response (ms)",
          width: 120,
          isSortable: true,
          filterable: true,
          isEditable: true,
          align: "right",
          type: "number",
          cellRenderer: InfraResponseCellComponent,
        },
      ],
    },
    {
      accessor: "status",
      label: "Status",
      width: 130,
      isSortable: true,
      filterable: true,
      isEditable: false,
      align: "center",
      type: "enum",
      enumOptions: [
        { label: "Online", value: "online" },
        { label: "Warning", value: "warning" },
        { label: "Critical", value: "critical" },
        { label: "Maintenance", value: "maintenance" },
        { label: "Offline", value: "offline" },
      ],
      valueGetter: ({ row }: ValueGetterProps) => {
        const m: Record<string, number> = { critical: 1, offline: 2, warning: 3, maintenance: 4, online: 5 };
        return m[String(row.status)] || 999;
      },
      cellRenderer: InfraStatusCellComponent,
    },
  ];
}

@Component({
  selector: "infrastructure-demo",
  standalone: true,
  imports: [SimpleTableComponent],
  template: `
    <simple-table
      #simpleTable
      [autoExpandColumns]="true"
      [columnReordering]="true"
      [columnResizing]="true"
      [defaultHeaders]="headers"
      [editColumns]="true"
      [height]="height"
      [rows]="rows"
      [selectableCells]="true"
      [theme]="theme"
    ></simple-table>
  `,
})
export class InfrastructureDemoComponent implements AfterViewInit, OnDestroy {
  @ViewChild("simpleTable") tableRef!: SimpleTableComponent;
  @Input() height: string | number = "400px";
  @Input() theme?: Theme;

  readonly rows: Row[] = infrastructureData;
  readonly headers: AngularHeaderObject[] = getHeaders();

  private cleanupFn?: () => void;

  ngAfterViewInit(): void {
    this.cleanupFn = startInfraDemoLiveUpdates(() => this.tableRef?.getAPI() ?? null, this.rows);
  }

  ngOnDestroy(): void {
    this.cleanupFn?.();
  }
}

// packages/examples/svelte/src/demos/infrastructure/InfrastructureDemo.svelte
<script lang="ts">
  import { SimpleTable } from "@simple-table/svelte";
  import type { Theme, SvelteHeaderObject, TableAPI, Row, CellValue } from "@simple-table/svelte";
  import { onMount } from "svelte";
  import { infrastructureData } from "./infrastructure.demo-data";
  import InfraServerIdCell from "./InfraServerIdCell.svelte";
  import InfraCpuCell from "./InfraCpuCell.svelte";
  import InfraMemoryCell from "./InfraMemoryCell.svelte";
  import InfraDiskCell from "./InfraDiskCell.svelte";
  import InfraResponseCell from "./InfraResponseCell.svelte";
  import InfraStatusCell from "./InfraStatusCell.svelte";
  import "@simple-table/svelte/styles.css";

  const INFRA_TICK_MS = 20;
  const INFRA_ROWS_PER_TICK = 4;
  type InfraMetricSlot = 0 | 1 | 2 | 3 | 4 | 5 | 6;

  function infraPickRandomSubset<T>(arr: T[], n: number): T[] {
    const copy = [...arr];
    for (let i = copy.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      const t = copy[i]!;
      copy[i] = copy[j]!;
      copy[j] = t;
    }
    return copy.slice(0, Math.min(n, copy.length));
  }

  function infraApplyRowPatch(api: TableAPI, rowIndex: number, patch: Partial<Row>) {
    for (const accessor of Object.keys(patch)) {
      const newValue = patch[accessor];
      if (newValue === undefined) continue;
      api.updateData({ accessor, rowIndex, newValue: newValue as CellValue });
    }
  }

  function infraComputeMetricPatch(row: Row, slot: InfraMetricSlot): Partial<Row> | null {
    switch (slot) {
      case 0: {
        const currentCpu = row.cpuUsage as number;
        if (typeof currentCpu !== "number") return null;
        const cpuChange = (Math.random() - 0.5) * 8;
        const newCpu = Math.min(100, Math.max(0, currentCpu + cpuChange));
        const newCpuRounded = Math.round(newCpu * 10) / 10;
        const currentHistory = row.cpuHistory as number[];
        if (Array.isArray(currentHistory) && currentHistory.length > 0) {
          return { cpuUsage: newCpuRounded, cpuHistory: [...currentHistory.slice(1), newCpuRounded] };
        }
        return { cpuUsage: newCpuRounded };
      }
      case 1: {
        const currentMemory = row.memoryUsage as number;
        if (typeof currentMemory !== "number") return null;
        const memoryChange = (Math.random() - 0.5) * 5;
        const newMemory = Math.min(100, Math.max(0, currentMemory + memoryChange));
        return { memoryUsage: Math.round(newMemory * 10) / 10 };
      }
      case 2: {
        const currentNetIn = row.networkIn as number;
        if (typeof currentNetIn !== "number") return null;
        const netChange = (Math.random() - 0.5) * 100;
        return { networkIn: Math.round(Math.max(0, currentNetIn + netChange) * 100) / 100 };
      }
      case 3: {
        const currentNetOut = row.networkOut as number;
        if (typeof currentNetOut !== "number") return null;
        const netChange = (Math.random() - 0.5) * 60;
        return { networkOut: Math.round(Math.max(0, currentNetOut + netChange) * 100) / 100 };
      }
      case 4: {
        const currentResponseTime = row.responseTime as number;
        if (typeof currentResponseTime !== "number") return null;
        const responseChange = (Math.random() - 0.5) * 100;
        return { responseTime: Math.round(Math.max(10, currentResponseTime + responseChange) * 10) / 10 };
      }
      case 5: {
        const currentConnections = row.activeConnections as number;
        if (typeof currentConnections !== "number") return null;
        const connectionChange = Math.floor((Math.random() - 0.5) * 500);
        return { activeConnections: Math.max(0, currentConnections + connectionChange) };
      }
      case 6: {
        const currentRequests = row.requestsPerSec as number;
        if (typeof currentRequests !== "number") return null;
        const requestChange = Math.floor((Math.random() - 0.5) * 2000);
        return { requestsPerSec: Math.max(0, currentRequests + requestChange) };
      }
      default:
        return null;
    }
  }

  function startInfraDemoLiveUpdates(getApi: () => TableAPI | null | undefined, rows: Row[]): () => void {
    let isActive = true;
    const idToIndex = new Map<string, number>();
    for (let i = 0; i < rows.length; i++) {
      idToIndex.set(String(rows[i]!.id), i);
    }
    const tick = () => {
      if (!isActive) return;
      const api = getApi();
      if (!api) return;
      const visible = api.getVisibleRows();
      if (!visible.length) return;
      const picks = infraPickRandomSubset(visible, INFRA_ROWS_PER_TICK);
      let usedCpuSparkline = false;
      for (const vr of picks) {
        const idx = idToIndex.get(String(vr.row.id));
        if (idx === undefined) continue;
        let slot = Math.floor(Math.random() * 7) as InfraMetricSlot;
        if (slot === 0 && usedCpuSparkline) slot = (1 + Math.floor(Math.random() * 6)) as InfraMetricSlot;
        if (slot === 0) usedCpuSparkline = true;
        const patch = infraComputeMetricPatch(vr.row, slot);
        if (patch) infraApplyRowPatch(api, idx, patch);
      }
    };
    tick();
    const intervalId = setInterval(tick, INFRA_TICK_MS);
    return () => {
      isActive = false;
      clearInterval(intervalId);
    };
  }

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();

  let tableRef: any;

  const headers = $derived.by(
    (): SvelteHeaderObject[] => [
      {
        accessor: "serverId",
        align: "left",
        filterable: true,
        isEditable: false,
        isSortable: true,
        label: "Server ID",
        minWidth: 180,
        pinned: "left",
        type: "string",
        width: "1.2fr",
        cellRenderer: InfraServerIdCell,
      },
      {
        accessor: "serverName",
        align: "left",
        filterable: true,
        isEditable: false,
        isSortable: true,
        label: "Name",
        minWidth: 200,
        type: "string",
        width: "1.5fr",
      },
      {
        accessor: "performance",
        label: "Performance Metrics",
        width: 690,
        isSortable: false,
        children: [
          {
            accessor: "cpuHistory",
            label: "CPU History",
            width: 150,
            isSortable: false,
            filterable: false,
            isEditable: false,
            align: "center",
            type: "lineAreaChart",
            tooltip: "CPU usage over the last 30 intervals",
          },
          {
            accessor: "cpuUsage",
            label: "CPU %",
            width: 120,
            isSortable: true,
            filterable: true,
            isEditable: true,
            align: "right",
            type: "number",
            cellRenderer: InfraCpuCell,
          },
          {
            accessor: "memoryUsage",
            label: "Memory %",
            width: 130,
            isSortable: true,
            filterable: true,
            isEditable: true,
            align: "right",
            type: "number",
            cellRenderer: InfraMemoryCell,
          },
          {
            accessor: "diskUsage",
            label: "Disk %",
            width: 120,
            isSortable: true,
            filterable: true,
            isEditable: true,
            align: "right",
            type: "number",
            cellRenderer: InfraDiskCell,
          },
          {
            accessor: "responseTime",
            label: "Response (ms)",
            width: 120,
            isSortable: true,
            filterable: true,
            isEditable: true,
            align: "right",
            type: "number",
            cellRenderer: InfraResponseCell,
          },
        ],
      },
      {
        accessor: "status",
        label: "Status",
        width: 130,
        isSortable: true,
        filterable: true,
        isEditable: false,
        align: "center",
        type: "enum",
        enumOptions: [
          { label: "Online", value: "online" },
          { label: "Warning", value: "warning" },
          { label: "Critical", value: "critical" },
          { label: "Maintenance", value: "maintenance" },
          { label: "Offline", value: "offline" },
        ],
        valueGetter: ({ row }) => {
          const s = String(row.status);
          const m: Record<string, number> = { critical: 1, offline: 2, warning: 3, maintenance: 4, online: 5 };
          return m[s] || 999;
        },
        cellRenderer: InfraStatusCell,
      },
    ],
  );

  onMount(() => {
    return startInfraDemoLiveUpdates(() => tableRef?.getAPI?.() ?? null, infrastructureData);
  });
</script>

<SimpleTable
  bind:this={tableRef}
  autoExpandColumns={true}
  columnReordering={true}
  columnResizing={true}
  defaultHeaders={headers}
  editColumns={true}
  {height}
  rows={infrastructureData}
  selectableCells={true}
  {theme}
/>
