// packages/examples/angular/src/demos/nested-tables/nested-tables-demo.component.ts
import { Component, Input } from "@angular/core";
import {SimpleTableComponent} from "@simple-table/angular";import type { AngularHeaderObject, Theme } from "@simple-table/angular";
import { nestedTablesConfig, generateNestedTablesData } from "./nested-tables.demo-data";
import "@simple-table/angular/styles.css";

@Component({
  selector: "nested-tables-demo",
  standalone: true,
  imports: [SimpleTableComponent],
  template: `
    <simple-table
      [autoExpandColumns]="true"
      [defaultHeaders]="headers"
      [rows]="sampleData"
      [rowGrouping]="grouping"
      [getRowId]="getRowId"
      [expandAll]="false"
      [columnResizing]="true"
      [height]="height"
      [theme]="theme"
    ></simple-table>
  `,
})
export class NestedTablesDemoComponent {
  @Input() height: string | number = "500px";
  @Input() theme?: Theme;

  readonly headers: AngularHeaderObject[] = nestedTablesConfig.headers;
  readonly sampleData = generateNestedTablesData(25);
  readonly grouping = ["divisions"];
  readonly getRowId = ({ row }: { row: Record<string, unknown> }) => row["id"] as string;
}

// packages/examples/solid/src/demos/nested-tables/NestedTablesDemo.tsx
import { createMemo } from "solid-js";
import {SimpleTable} from "@simple-table/solid";import type { Theme } from "@simple-table/solid";
import { nestedTablesConfig, generateNestedTablesData } from "./nested-tables.demo-data";
import "@simple-table/solid/styles.css";

export default function NestedTablesDemo(props: { height?: string | number; theme?: Theme }) {
  const sampleData = createMemo(() => generateNestedTablesData(25));

  return (
    <SimpleTable
      autoExpandColumns={nestedTablesConfig.tableProps.autoExpandColumns}
      defaultHeaders={nestedTablesConfig.headers}
      rows={sampleData()}
      rowGrouping={nestedTablesConfig.tableProps.rowGrouping}
      getRowId={nestedTablesConfig.tableProps.getRowId}
      expandAll={nestedTablesConfig.tableProps.expandAll}
      columnResizing={nestedTablesConfig.tableProps.columnResizing}
      height={props.height ?? "500px"}
      theme={props.theme}
    />
  );
}
