// packages/examples/solid/src/demos/column-sorting/ColumnSortingDemo.tsx
import {SimpleTable} from "@simple-table/solid";import type { Theme } from "@simple-table/solid";
import { columnSortingConfig } from "./column-sorting.demo-data";
import "@simple-table/solid/styles.css";

export default function ColumnSortingDemo(props: {
  height?: string | number;
  theme?: Theme;
}) {
  return (
    <SimpleTable
      defaultHeaders={columnSortingConfig.headers}
      rows={columnSortingConfig.rows}
      height={props.height ?? "400px"}
      theme={props.theme}
      initialSortColumn={columnSortingConfig.tableProps.initialSortColumn}
      initialSortDirection={columnSortingConfig.tableProps.initialSortDirection}
    />
  );
}

// packages/examples/angular/src/demos/column-sorting/column-sorting-demo.component.ts
import { Component, Input } from "@angular/core";
import {SimpleTableComponent} from "@simple-table/angular";import type { AngularHeaderObject, Row, Theme } from "@simple-table/angular";
import { columnSortingConfig } from "./column-sorting.demo-data";
import "@simple-table/angular/styles.css";

@Component({
  selector: "column-sorting-demo",
  standalone: true,
  imports: [SimpleTableComponent],
  template: `
    <simple-table
      [rows]="rows"
      [defaultHeaders]="headers"
      [height]="height"
      [theme]="theme"
      [initialSortColumn]="initialSortColumn"
      [initialSortDirection]="initialSortDirection"
    ></simple-table>
  `,
})
export class ColumnSortingDemoComponent {
  @Input() height: string | number = "400px";
  @Input() theme?: Theme;

  readonly rows: Row[] = columnSortingConfig.rows;
  readonly headers: AngularHeaderObject[] = columnSortingConfig.headers;
  readonly initialSortColumn = columnSortingConfig.tableProps.initialSortColumn;
  readonly initialSortDirection = columnSortingConfig.tableProps.initialSortDirection;
}
