// packages/examples/react/src/demos/cell-clicking/CellClickingDemo.tsx
import { useState, useMemo } from "react";
import { SimpleTable } from "@simple-table/react";
import type {
  Theme,
  ReactHeaderObject,
  CellRendererProps,
  CellClickProps,
} from "@simple-table/react";
import {
  cellClickingHeaders,
  cellClickingData,
  CELL_CLICKING_STATUSES,
} from "./cell-clicking.demo-data";
import type { ProjectTask } from "./cell-clicking.demo-data";
import "@simple-table/react/styles.css";

const CellClickingDemo = ({ height, theme }: { height?: string | number; theme?: Theme }) => {
  const [clickInfo, setClickInfo] = useState("");
  const [selectedTask, setSelectedTask] = useState<ProjectTask | null>(null);
  const [rows, setRows] = useState<ProjectTask[]>([...cellClickingData]);

  const headers: ReactHeaderObject[] = useMemo(
    () =>
      cellClickingHeaders.map((h) => {
        if (h.accessor === "priority") {
          return {
            ...h,
            cellRenderer: ({ row }: CellRendererProps) => {
              const p = String(row.priority);
              return (
                <span
                  style={{
                    color: p === "High" ? "#ef4444" : p === "Medium" ? "#f59e0b" : "#10b981",
                    fontWeight: "bold",
                    cursor: "pointer",
                  }}
                  title="Click to filter by priority"
                >
                  {p}
                </span>
              );
            },
          };
        }
        if (h.accessor === "status") {
          return {
            ...h,
            cellRenderer: ({ row }: CellRendererProps) => {
              const s = String(row.status);
              const bg =
                s === "Completed" ? "#dcfce7" : s === "In Progress" ? "#fef3c7" : "#fee2e2";
              const color =
                s === "Completed" ? "#166534" : s === "In Progress" ? "#92400e" : "#991b1b";
              return (
                <span
                  style={{
                    backgroundColor: bg,
                    color,
                    padding: "4px 8px",
                    borderRadius: 4,
                    fontSize: 12,
                    fontWeight: "bold",
                    cursor: "pointer",
                  }}
                  title="Click to change status"
                >
                  {s}
                </span>
              );
            },
          };
        }
        if (h.accessor === "details") {
          return {
            ...h,
            cellRenderer: () => (
              <button
                style={{
                  backgroundColor: "#3b82f6",
                  color: "white",
                  border: "none",
                  padding: "6px 12px",
                  borderRadius: 4,
                  cursor: "pointer",
                  fontSize: 12,
                  fontWeight: "bold",
                }}
                title="Click to view task details"
              >
                View Details
              </button>
            ),
          };
        }
        return h;
      }),
    [],
  );

  const handleCellClick = ({ accessor, rowIndex, value, row }: CellClickProps) => {
    const task = row as ProjectTask;
    switch (accessor) {
      case "priority": {
        setClickInfo(`Filtering by ${value} priority`);
        setRows(cellClickingData.filter((t) => t.priority === value));
        break;
      }
      case "status": {
        const idx = CELL_CLICKING_STATUSES.indexOf(String(value));
        const next = CELL_CLICKING_STATUSES[(idx + 1) % CELL_CLICKING_STATUSES.length];
        setRows((prev) => prev.map((t) => (t.id === task.id ? { ...t, status: next } : t)));
        setClickInfo(`Status changed from "${value}" to "${next}"`);
        break;
      }
      case "details":
        setSelectedTask(task);
        setClickInfo(`Opening details for: ${task.task}`);
        break;
      case "estimatedHours": {
        const newVal = Math.min(task.estimatedHours + 2, 40);
        setRows((prev) =>
          prev.map((t) => (t.id === task.id ? { ...t, estimatedHours: newVal } : t)),
        );
        setClickInfo(`Est. hours: ${task.estimatedHours}h → ${newVal}h`);
        break;
      }
      case "completedHours": {
        const newVal = Math.min(task.completedHours + 1, task.estimatedHours);
        setRows((prev) =>
          prev.map((t) => (t.id === task.id ? { ...t, completedHours: newVal } : t)),
        );
        setClickInfo(`Done hours: ${task.completedHours}h → ${newVal}h`);
        break;
      }
      default:
        setClickInfo(`Clicked [${accessor}] = "${value}" (row ${rowIndex})`);
    }
  };

  const isDark = theme === "modern-dark" || theme === "dark";

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
      <div
        style={{
          padding: 12,
          backgroundColor: isDark ? "#374151" : "#f3f4f6",
          borderRadius: 8,
          border: `1px solid ${isDark ? "#4b5563" : "#d1d5db"}`,
          minHeight: 48,
          display: "flex",
          alignItems: "center",
        }}
      >
        <strong style={{ marginRight: 8, color: isDark ? "#f9fafb" : "#1f2937" }}>
          Last Click:
        </strong>
        <span style={{ color: isDark ? "#d1d5db" : "#4b5563" }}>
          {clickInfo || "Click any cell to see interaction details..."}
        </span>
      </div>

      {selectedTask && (
        <div
          style={{
            position: "fixed",
            inset: 0,
            backgroundColor: "rgba(0,0,0,0.5)",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            zIndex: 1000,
          }}
        >
          <div
            style={{
              backgroundColor: isDark ? "#1f2937" : "white",
              padding: 24,
              borderRadius: 8,
              maxWidth: 500,
              width: "90%",
            }}
          >
            <h3 style={{ margin: "0 0 16px", color: isDark ? "#f9fafb" : "#1f2937" }}>
              Task Details
            </h3>
            {(["task", "details", "assignee", "status", "priority"] as const).map((key) => (
              <p key={key} style={{ margin: "8px 0", color: isDark ? "#d1d5db" : "#4b5563" }}>
                <strong>{key.charAt(0).toUpperCase() + key.slice(1)}:</strong> {selectedTask[key]}
              </p>
            ))}
            <button
              onClick={() => setSelectedTask(null)}
              style={{
                marginTop: 16,
                backgroundColor: "#3b82f6",
                color: "white",
                border: "none",
                padding: "8px 16px",
                borderRadius: 4,
                cursor: "pointer",
                fontWeight: "bold",
              }}
            >
              Close
            </button>
          </div>
        </div>
      )}

      <SimpleTable
        columnResizing
        defaultHeaders={headers}
        height={height ?? "320px"}
        onCellClick={handleCellClick}
        rows={rows}
        theme={theme}
      />
    </div>
  );
};

export default CellClickingDemo;

// packages/examples/solid/src/demos/cell-clicking/CellClickingDemo.tsx
import { createSignal, createMemo, Show, For } from "solid-js";
import {SimpleTable} from "@simple-table/solid";import type { Theme, SolidHeaderObject, CellRendererProps, CellClickProps } from "@simple-table/solid";
import { cellClickingHeaders, cellClickingData, CELL_CLICKING_STATUSES } from "./cell-clicking.demo-data";
import type { ProjectTask } from "./cell-clicking.demo-data";
import "@simple-table/solid/styles.css";

const DETAIL_KEYS = ["task", "details", "assignee", "status", "priority"] as const;

export default function CellClickingDemo(props: { height?: string | number; theme?: Theme }) {
  const [clickInfo, setClickInfo] = createSignal("");
  const [selectedTask, setSelectedTask] = createSignal<ProjectTask | null>(null);
  const [rows, setRows] = createSignal<ProjectTask[]>([...cellClickingData]);

  const headers: SolidHeaderObject[] = cellClickingHeaders.map((h) => {
    if (h.accessor === "priority") {
      return {
        ...h,
        cellRenderer: (cr: CellRendererProps) => {
          const p = String(cr.row.priority);
          const color = p === "High" ? "#ef4444" : p === "Medium" ? "#f59e0b" : "#10b981";
          return (
            <span style={{ color, "font-weight": "bold", cursor: "pointer" }} title="Click to filter">
              {p}
            </span>
          );
        },
      };
    }
    if (h.accessor === "status") {
      return {
        ...h,
        cellRenderer: (cr: CellRendererProps) => {
          const s = String(cr.row.status);
          const bg = s === "Completed" ? "#dcfce7" : s === "In Progress" ? "#fef3c7" : "#fee2e2";
          const c = s === "Completed" ? "#166534" : s === "In Progress" ? "#92400e" : "#991b1b";
          return (
            <span
              style={{
                background: bg,
                color: c,
                padding: "4px 8px",
                "border-radius": "4px",
                "font-size": "12px",
                "font-weight": "bold",
                cursor: "pointer",
              }}
              title="Click to change"
            >
              {s}
            </span>
          );
        },
      };
    }
    if (h.accessor === "details") {
      return {
        ...h,
        cellRenderer: () => (
          <button
            type="button"
            style={{
              background: "#3b82f6",
              color: "white",
              border: "none",
              padding: "6px 12px",
              "border-radius": "4px",
              cursor: "pointer",
              "font-size": "12px",
              "font-weight": "bold",
            }}
          >
            View Details
          </button>
        ),
      };
    }
    return h;
  });

  const isDark = createMemo(() => props.theme === "modern-dark" || props.theme === "dark");

  const handleCellClick = ({ accessor, rowIndex, value, row }: CellClickProps) => {
    const task = row as ProjectTask;
    switch (accessor) {
      case "priority":
        setClickInfo(`Filtering by ${value} priority`);
        setRows(cellClickingData.filter((t) => t.priority === value));
        break;
      case "status": {
        const idx = CELL_CLICKING_STATUSES.indexOf(String(value));
        const next = CELL_CLICKING_STATUSES[(idx + 1) % CELL_CLICKING_STATUSES.length];
        setRows((prev) => prev.map((t) => (t.id === task.id ? { ...t, status: next } : t)));
        setClickInfo(`Status: "${value}" → "${next}"`);
        break;
      }
      case "details":
        setSelectedTask(task);
        setClickInfo(`Opening details for: ${task.task}`);
        break;
      case "estimatedHours": {
        const n = Math.min(task.estimatedHours + 2, 40);
        setRows((prev) => prev.map((t) => (t.id === task.id ? { ...t, estimatedHours: n } : t)));
        setClickInfo(`Est. hours: ${task.estimatedHours}h → ${n}h`);
        break;
      }
      case "completedHours": {
        const n = Math.min(task.completedHours + 1, task.estimatedHours);
        setRows((prev) => prev.map((t) => (t.id === task.id ? { ...t, completedHours: n } : t)));
        setClickInfo(`Done hours: ${task.completedHours}h → ${n}h`);
        break;
      }
      default:
        setClickInfo(`Clicked [${accessor}] = "${value}" (row ${rowIndex})`);
    }
  };

  return (
    <div style={{ display: "flex", "flex-direction": "column", gap: "16px" }}>
      <div
        style={{
          padding: "12px",
          "background-color": isDark() ? "#374151" : "#f3f4f6",
          "border-radius": "8px",
          border: `1px solid ${isDark() ? "#4b5563" : "#d1d5db"}`,
          "min-height": "48px",
          display: "flex",
          "align-items": "center",
        }}
      >
        <strong style={{ "margin-right": "8px", color: isDark() ? "#f9fafb" : "#1f2937" }}>Last Click:</strong>
        <span style={{ color: isDark() ? "#d1d5db" : "#4b5563" }}>
          {clickInfo() || "Click any cell to see interaction details..."}
        </span>
      </div>

      <Show when={selectedTask()}>
        {(task) => (
          <div
            style={{
              position: "fixed",
              inset: "0",
              background: "rgba(0,0,0,0.5)",
              display: "flex",
              "align-items": "center",
              "justify-content": "center",
              "z-index": 1000,
            }}
          >
            <div
              style={{
                background: isDark() ? "#1f2937" : "white",
                padding: "24px",
                "border-radius": "8px",
                "max-width": "500px",
                width: "90%",
              }}
            >
              <h3 style={{ margin: "0 0 16px", color: isDark() ? "#f9fafb" : "#1f2937" }}>Task Details</h3>
              <For each={DETAIL_KEYS}>
                {(key) => (
                  <p style={{ margin: "8px 0", color: isDark() ? "#d1d5db" : "#4b5563" }}>
                    <strong>{key.charAt(0).toUpperCase() + key.slice(1)}:</strong> {String(task()[key])}
                  </p>
                )}
              </For>
              <button
                type="button"
                onClick={() => setSelectedTask(null)}
                style={{
                  "margin-top": "16px",
                  background: "#3b82f6",
                  color: "white",
                  border: "none",
                  padding: "8px 16px",
                  "border-radius": "4px",
                  cursor: "pointer",
                  "font-weight": "bold",
                }}
              >
                Close
              </button>
            </div>
          </div>
        )}
      </Show>

      <SimpleTable
        columnResizing
        defaultHeaders={headers}
        height={props.height ?? "320px"}
        onCellClick={handleCellClick}
        rows={rows()}
        theme={props.theme}
      />
    </div>
  );
}
